//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VsoWorkItemsSync.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BugRevision
    {
        public long ID { get; set; }
        public int Rev { get; set; }
        public string Work_Item_Type { get; set; }
        public string Title { get; set; }
        public string Assigned_To { get; set; }
        public string State { get; set; }
        public string Tags { get; set; }
        public string Area_Path { get; set; }
        public string Branch_Found { get; set; }
        public string Build_Found { get; set; }
        public string Changed_By { get; set; }
        public Nullable<System.DateTime> Changed_Date { get; set; }
        public string Closed_By { get; set; }
        public Nullable<System.DateTime> Closed_Date { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> Due_Date { get; set; }
        public string Fix_Provided_By { get; set; }
        public string Fixed_Build { get; set; }
        public string How_Was_Found { get; set; }
        public string Issue_Type { get; set; }
        public string Iteration_Path { get; set; }
        public string Keywords { get; set; }
        public string Language { get; set; }
        public Nullable<double> Priority { get; set; }
        public string PS_Database { get; set; }
        public string PS_ID { get; set; }
        public string Resolved_By { get; set; }
        public Nullable<System.DateTime> Resolved_Date { get; set; }
        public string Severity { get; set; }
        public string Skype_Priority { get; set; }
        public string Source { get; set; }
        public string Team_Project { get; set; }
        public string Root_Cause_Category { get; set; }
        public string Reason { get; set; }
        public string Resolved_Reason { get; set; }
        public string Issue_Subtype { get; set; }
        public string Triaged { get; set; }
        public Nullable<int> Estimated_Test_Impact { get; set; }
        public string Fabric_Project { get; set; }
        public string File_Name { get; set; }
        public string Resource_ID { get; set; }
        public string Source_String { get; set; }
        public string Original_Translation { get; set; }
        public string Suggested_Translation { get; set; }
        public string Fix_Type { get; set; }
    }
}
