using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace LocaLiz.Models
{
    public class LocaLizDataContext : DbContext
    {
        public LocaLizDataContext() : base("LocaLizDataContext")
        {

        }

        public DbSet<UserModel> Users { get; set; }
        public DbSet<TranslationOriginalModel> ResourceStrings { get; set; }
        public DbSet<TranslationFeedbackModel> TranslationFeedbacks { get; set; }
        public DbSet<SuggestedTranslationModel> SuggestedTranslations { get; set; }

        public DbSet<SuggestedTranslationFeedback> SuggestedTranslationFeedbacks { get; set; }

        public DbSet<UserLanguageModel> UserLanguages { get; set; }

        public DbSet<LanguageModel> Languages { get; set; }
        public DbSet<ConversationModel> Stuffs { get; set; }
    }

    public class LocalizInitializer : System.Data.Entity.DropCreateDatabaseIfModelChanges<LocaLizDataContext>
    {
        protected override void Seed(LocaLizDataContext context)
        {
            var languages = new List<LanguageModel>
            {
               new LanguageModel() {ISO="aa",NameInEnglish="Afar"},
                new LanguageModel() {ISO="ab",NameInEnglish="Abkhazian"},
                new LanguageModel() {ISO="af",NameInEnglish="Afrikaans"},
                new LanguageModel() {ISO="ak",NameInEnglish="Akan"},
                new LanguageModel() {ISO="sq",NameInEnglish="Albanian"},
                new LanguageModel() {ISO="am",NameInEnglish="Amharic"},
                new LanguageModel() {ISO="ar",NameInEnglish="Arabic"},
                new LanguageModel() {ISO="an",NameInEnglish="Aragonese"},
                new LanguageModel() {ISO="hy",NameInEnglish="Armenian"},
                new LanguageModel() {ISO="as",NameInEnglish="Assamese"},
                new LanguageModel() {ISO="av",NameInEnglish="Avaric"},
                new LanguageModel() {ISO="ae",NameInEnglish="Avestan"},
                new LanguageModel() {ISO="ay",NameInEnglish="Aymara"},
                new LanguageModel() {ISO="az",NameInEnglish="Azerbaijani"},
                new LanguageModel() {ISO="ba",NameInEnglish="Bashkir"},
                new LanguageModel() {ISO="bm",NameInEnglish="Bambara"},
                new LanguageModel() {ISO="eu",NameInEnglish="Basque"},
                new LanguageModel() {ISO="be",NameInEnglish="Belarusian"},
                new LanguageModel() {ISO="bn",NameInEnglish="Bengali"},
                new LanguageModel() {ISO="bh",NameInEnglish="Bihari languages"},
                new LanguageModel() {ISO="bi",NameInEnglish="Bislama"},
                new LanguageModel() {ISO="bo",NameInEnglish="Tibetan"},
                new LanguageModel() {ISO="bs",NameInEnglish="Bosnian"},
                new LanguageModel() {ISO="br",NameInEnglish="Breton"},
                new LanguageModel() {ISO="bg",NameInEnglish="Bulgarian"},
                new LanguageModel() {ISO="my",NameInEnglish="Burmese"},
                new LanguageModel() {ISO="ca",NameInEnglish="Catalan; Valencian"},
                new LanguageModel() {ISO="cs",NameInEnglish="Czech"},
                new LanguageModel() {ISO="ch",NameInEnglish="Chamorro"},
                new LanguageModel() {ISO="ce",NameInEnglish="Chechen"},
                new LanguageModel() {ISO="zh",NameInEnglish="Chinese"},
                new LanguageModel() {ISO="cu",NameInEnglish="Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic"},
                new LanguageModel() {ISO="cv",NameInEnglish="Chuvash"},
                new LanguageModel() {ISO="kw",NameInEnglish="Cornish"},
                new LanguageModel() {ISO="co",NameInEnglish="Corsican"},
                new LanguageModel() {ISO="cr",NameInEnglish="Cree"},
                new LanguageModel() {ISO="cy",NameInEnglish="Welsh"},
                new LanguageModel() {ISO="cs",NameInEnglish="Czech"},
                new LanguageModel() {ISO="da",NameInEnglish="Danish"},
                new LanguageModel() {ISO="de",NameInEnglish="German"},
                new LanguageModel() {ISO="dv",NameInEnglish="Divehi; Dhivehi; Maldivian"},
                new LanguageModel() {ISO="nl",NameInEnglish="Dutch; Flemish"},
                new LanguageModel() {ISO="dz",NameInEnglish="Dzongkha"},
                new LanguageModel() {ISO="el",NameInEnglish="Greek, Modern (1453-)"},
                new LanguageModel() {ISO="en",NameInEnglish="English"},
                new LanguageModel() {ISO="eo",NameInEnglish="Esperanto"},
                new LanguageModel() {ISO="et",NameInEnglish="Estonian"},
                new LanguageModel() {ISO="eu",NameInEnglish="Basque"},
                new LanguageModel() {ISO="ee",NameInEnglish="Ewe"},
                new LanguageModel() {ISO="fo",NameInEnglish="Faroese"},
                new LanguageModel() {ISO="fa",NameInEnglish="Persian"},
                new LanguageModel() {ISO="fj",NameInEnglish="Fijian"},
                new LanguageModel() {ISO="fi",NameInEnglish="Finnish"},
                new LanguageModel() {ISO="fr",NameInEnglish="French"},
                new LanguageModel() {ISO="fr",NameInEnglish="French"},
                new LanguageModel() {ISO="fy",NameInEnglish="Western Frisian"},
                new LanguageModel() {ISO="ff",NameInEnglish="Fulah"},
                new LanguageModel() {ISO="ka",NameInEnglish="Georgian"},
                new LanguageModel() {ISO="de",NameInEnglish="German"},
                new LanguageModel() {ISO="gd",NameInEnglish="Gaelic; Scottish Gaelic"},
                new LanguageModel() {ISO="ga",NameInEnglish="Irish"},
                new LanguageModel() {ISO="gl",NameInEnglish="Galician"},
                new LanguageModel() {ISO="gv",NameInEnglish="Manx"},
                new LanguageModel() {ISO="el",NameInEnglish="Greek, Modern (1453-)"},
                new LanguageModel() {ISO="gn",NameInEnglish="Guarani"},
                new LanguageModel() {ISO="gu",NameInEnglish="Gujarati"},
                new LanguageModel() {ISO="ht",NameInEnglish="Haitian; Haitian Creole"},
                new LanguageModel() {ISO="ha",NameInEnglish="Hausa"},
                new LanguageModel() {ISO="he",NameInEnglish="Hebrew"},
                new LanguageModel() {ISO="hz",NameInEnglish="Herero"},
                new LanguageModel() {ISO="hi",NameInEnglish="Hindi"},
                new LanguageModel() {ISO="ho",NameInEnglish="Hiri Motu"},
                new LanguageModel() {ISO="hr",NameInEnglish="Croatian"},
                new LanguageModel() {ISO="hu",NameInEnglish="Hungarian"},
                new LanguageModel() {ISO="hy",NameInEnglish="Armenian"},
                new LanguageModel() {ISO="ig",NameInEnglish="Igbo"},
                new LanguageModel() {ISO="is",NameInEnglish="Icelandic"},
                new LanguageModel() {ISO="io",NameInEnglish="Ido"},
                new LanguageModel() {ISO="ii",NameInEnglish="Sichuan Yi; Nuosu"},
                new LanguageModel() {ISO="iu",NameInEnglish="Inuktitut"},
                new LanguageModel() {ISO="ie",NameInEnglish="Interlingue; Occidental"},
                new LanguageModel() {ISO="ia",NameInEnglish="Interlingua (International Auxiliary Language Association)"},
                new LanguageModel() {ISO="id",NameInEnglish="Indonesian"},
                new LanguageModel() {ISO="ik",NameInEnglish="Inupiaq"},
                new LanguageModel() {ISO="is",NameInEnglish="Icelandic"},
                new LanguageModel() {ISO="it",NameInEnglish="Italian"},
                new LanguageModel() {ISO="jv",NameInEnglish="Javanese"},
                new LanguageModel() {ISO="ja",NameInEnglish="Japanese"},
                new LanguageModel() {ISO="kl",NameInEnglish="Kalaallisut; Greenlandic"},
                new LanguageModel() {ISO="kn",NameInEnglish="Kannada"},
                new LanguageModel() {ISO="ks",NameInEnglish="Kashmiri"},
                new LanguageModel() {ISO="ka",NameInEnglish="Georgian"},
                new LanguageModel() {ISO="kr",NameInEnglish="Kanuri"},
                new LanguageModel() {ISO="kk",NameInEnglish="Kazakh"},
                new LanguageModel() {ISO="km",NameInEnglish="Central Khmer"},
                new LanguageModel() {ISO="ki",NameInEnglish="Kikuyu; Gikuyu"},
                new LanguageModel() {ISO="rw",NameInEnglish="Kinyarwanda"},
                new LanguageModel() {ISO="ky",NameInEnglish="Kirghiz; Kyrgyz"},
                new LanguageModel() {ISO="kv",NameInEnglish="Komi"},
                new LanguageModel() {ISO="kg",NameInEnglish="Kongo"},
                new LanguageModel() {ISO="ko",NameInEnglish="Korean"},
                new LanguageModel() {ISO="kj",NameInEnglish="Kuanyama; Kwanyama"},
                new LanguageModel() {ISO="ku",NameInEnglish="Kurdish"},
                new LanguageModel() {ISO="lo",NameInEnglish="Lao"},
                new LanguageModel() {ISO="la",NameInEnglish="Latin"},
                new LanguageModel() {ISO="lv",NameInEnglish="Latvian"},
                new LanguageModel() {ISO="li",NameInEnglish="Limburgan; Limburger; Limburgish"},
                new LanguageModel() {ISO="ln",NameInEnglish="Lingala"},
                new LanguageModel() {ISO="lt",NameInEnglish="Lithuanian"},
                new LanguageModel() {ISO="lb",NameInEnglish="Luxembourgish; Letzeburgesch"},
                new LanguageModel() {ISO="lu",NameInEnglish="Luba-Katanga"},
                new LanguageModel() {ISO="lg",NameInEnglish="Ganda"},
                new LanguageModel() {ISO="mk",NameInEnglish="Macedonian"},
                new LanguageModel() {ISO="mh",NameInEnglish="Marshallese"},
                new LanguageModel() {ISO="ml",NameInEnglish="Malayalam"},
                new LanguageModel() {ISO="mi",NameInEnglish="Maori"},
                new LanguageModel() {ISO="mr",NameInEnglish="Marathi"},
                new LanguageModel() {ISO="ms",NameInEnglish="Malay"},
                new LanguageModel() {ISO="mk",NameInEnglish="Macedonian"},
                new LanguageModel() {ISO="mg",NameInEnglish="Malagasy"},
                new LanguageModel() {ISO="mt",NameInEnglish="Maltese"},
                new LanguageModel() {ISO="mn",NameInEnglish="Mongolian"},
                new LanguageModel() {ISO="mi",NameInEnglish="Maori"},
                new LanguageModel() {ISO="ms",NameInEnglish="Malay"},
                new LanguageModel() {ISO="my",NameInEnglish="Burmese"},
                new LanguageModel() {ISO="na",NameInEnglish="Nauru"},
                new LanguageModel() {ISO="nv",NameInEnglish="Navajo; Navaho"},
                new LanguageModel() {ISO="nr",NameInEnglish="Ndebele, South; South Ndebele"},
                new LanguageModel() {ISO="nd",NameInEnglish="Ndebele, North; North Ndebele"},
                new LanguageModel() {ISO="ng",NameInEnglish="Ndonga"},
                new LanguageModel() {ISO="ne",NameInEnglish="Nepali"},
                new LanguageModel() {ISO="nl",NameInEnglish="Dutch; Flemish"},
                new LanguageModel() {ISO="nn",NameInEnglish="Norwegian Nynorsk; Nynorsk, Norwegian"},
                new LanguageModel() {ISO="nb",NameInEnglish="Bokmål, Norwegian; Norwegian Bokmål"},
                new LanguageModel() {ISO="no",NameInEnglish="Norwegian"},
                new LanguageModel() {ISO="ny",NameInEnglish="Chichewa; Chewa; Nyanja"},
                new LanguageModel() {ISO="oc",NameInEnglish="Occitan (post 1500)"},
                new LanguageModel() {ISO="oj",NameInEnglish="Ojibwa"},
                new LanguageModel() {ISO="or",NameInEnglish="Oriya"},
                new LanguageModel() {ISO="om",NameInEnglish="Oromo"},
                new LanguageModel() {ISO="os",NameInEnglish="Ossetian; Ossetic"},
                new LanguageModel() {ISO="pa",NameInEnglish="Panjabi; Punjabi"},
                new LanguageModel() {ISO="fa",NameInEnglish="Persian"},
                new LanguageModel() {ISO="pi",NameInEnglish="Pali"},
                new LanguageModel() {ISO="pl",NameInEnglish="Polish"},
                new LanguageModel() {ISO="pt",NameInEnglish="Portuguese"},
                new LanguageModel() {ISO="ps",NameInEnglish="Pushto; Pashto"},
                new LanguageModel() {ISO="qu",NameInEnglish="Quechua"},
                new LanguageModel() {ISO="rm",NameInEnglish="Romansh"},
                new LanguageModel() {ISO="ro",NameInEnglish="Romanian; Moldavian; Moldovan"},
                new LanguageModel() {ISO="ro",NameInEnglish="Romanian; Moldavian; Moldovan"},
                new LanguageModel() {ISO="rn",NameInEnglish="Rundi"},
                new LanguageModel() {ISO="ru",NameInEnglish="Russian"},
                new LanguageModel() {ISO="sg",NameInEnglish="Sango"},
                new LanguageModel() {ISO="sa",NameInEnglish="Sanskrit"},
                new LanguageModel() {ISO="si",NameInEnglish="Sinhala; Sinhalese"},
                new LanguageModel() {ISO="sk",NameInEnglish="Slovak"},
                new LanguageModel() {ISO="sk",NameInEnglish="Slovak"},
                new LanguageModel() {ISO="sl",NameInEnglish="Slovenian"},
                new LanguageModel() {ISO="se",NameInEnglish="Northern Sami"},
                new LanguageModel() {ISO="sm",NameInEnglish="Samoan"},
                new LanguageModel() {ISO="sn",NameInEnglish="Shona"},
                new LanguageModel() {ISO="sd",NameInEnglish="Sindhi"},
                new LanguageModel() {ISO="so",NameInEnglish="Somali"},
                new LanguageModel() {ISO="st",NameInEnglish="Sotho, Southern"},
                new LanguageModel() {ISO="es",NameInEnglish="Spanish; Castilian"},
                new LanguageModel() {ISO="sq",NameInEnglish="Albanian"},
                new LanguageModel() {ISO="sc",NameInEnglish="Sardinian"},
                new LanguageModel() {ISO="sr",NameInEnglish="Serbian"},
                new LanguageModel() {ISO="ss",NameInEnglish="Swati"},
                new LanguageModel() {ISO="su",NameInEnglish="Sundanese"},
                new LanguageModel() {ISO="sw",NameInEnglish="Swahili"},
                new LanguageModel() {ISO="sv",NameInEnglish="Swedish"},
                new LanguageModel() {ISO="ty",NameInEnglish="Tahitian"},
                new LanguageModel() {ISO="ta",NameInEnglish="Tamil"},
                new LanguageModel() {ISO="tt",NameInEnglish="Tatar"},
                new LanguageModel() {ISO="te",NameInEnglish="Telugu"},
                new LanguageModel() {ISO="tg",NameInEnglish="Tajik"},
                new LanguageModel() {ISO="tl",NameInEnglish="Tagalog"},
                new LanguageModel() {ISO="th",NameInEnglish="Thai"},
                new LanguageModel() {ISO="bo",NameInEnglish="Tibetan"},
                new LanguageModel() {ISO="ti",NameInEnglish="Tigrinya"},
                new LanguageModel() {ISO="to",NameInEnglish="Tonga (Tonga Islands)"},
                new LanguageModel() {ISO="tn",NameInEnglish="Tswana"},
                new LanguageModel() {ISO="ts",NameInEnglish="Tsonga"},
                new LanguageModel() {ISO="tk",NameInEnglish="Turkmen"},
                new LanguageModel() {ISO="tr",NameInEnglish="Turkish"},
                new LanguageModel() {ISO="tw",NameInEnglish="Twi"},
                new LanguageModel() {ISO="ug",NameInEnglish="Uighur; Uyghur"},
                new LanguageModel() {ISO="uk",NameInEnglish="Ukrainian"},
                new LanguageModel() {ISO="ur",NameInEnglish="Urdu"},
                new LanguageModel() {ISO="uz",NameInEnglish="Uzbek"},
                new LanguageModel() {ISO="ve",NameInEnglish="Venda"},
                new LanguageModel() {ISO="vi",NameInEnglish="Vietnamese"},
                new LanguageModel() {ISO="vo",NameInEnglish="Volapük"},
                new LanguageModel() {ISO="cy",NameInEnglish="Welsh"},
                new LanguageModel() {ISO="wa",NameInEnglish="Walloon"},
                new LanguageModel() {ISO="wo",NameInEnglish="Wolof"},
                new LanguageModel() {ISO="xh",NameInEnglish="Xhosa"},
                new LanguageModel() {ISO="yi",NameInEnglish="Yiddish"},
                new LanguageModel() {ISO="yo",NameInEnglish="Yoruba"},
                new LanguageModel() {ISO="za",NameInEnglish="Zhuang; Chuang"},
                new LanguageModel() {ISO="zh",NameInEnglish="Chinese"},
                new LanguageModel() {ISO="zu",NameInEnglish="Zulu"}
            };
            languages.ForEach(x => context.Languages.Add(x));
            context.SaveChanges();
        }
    }
}