//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkypeIntlMonitoring.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientToolsDownload
    {
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string folder_binary { get; set; }
        public string version { get; set; }
        public System.DateTime last_updated_datetime { get; set; }
        public string folder_zip { get; set; }
        public int downloads { get; set; }
    }
}
