//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkypeIntlMonitoring.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogFile
    {
        public int LogID { get; set; }
        public int ToolID { get; set; }
        public string FullPath { get; set; }
    
        public virtual Tool Tool { get; set; }
    }
}
