//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkypeIntlMonitoring.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SqlJobStepIteration
    {
        public int SqlJobStepIterationID { get; set; }
        public System.Guid SqlJobID { get; set; }
        public int SqlJobStepID { get; set; }
        public Nullable<System.DateTime> RunDateTime { get; set; }
        public Nullable<int> RunDuration { get; set; }
        public Nullable<int> RunDurationMinutes { get; set; }
        public Nullable<int> Job_Run_Status_ID { get; set; }
        public string Outcome_Message { get; set; }
        public Nullable<int> ParentIterationID { get; set; }
    
        public virtual SqlJobStep SqlJobStep { get; set; }
        public virtual JobRunStatus JobRunStatus { get; set; }
    }
}
