//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkypeIntlMonitoring.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SqlJobStep
    {
        public SqlJobStep()
        {
            this.SqlJobStepIterations = new HashSet<SqlJobStepIteration>();
        }
    
        public int SqlJobStepID { get; set; }
        public System.Guid SqlJobID { get; set; }
        public string Name { get; set; }
        public string Command { get; set; }
        public Nullable<int> ToolID { get; set; }
        public Nullable<int> LastRunOutcome { get; set; }
        public Nullable<System.DateTime> LastRunDateTime { get; set; }
        public Nullable<int> LastRunDuration { get; set; }
        public Nullable<int> LastRunDurationMinutes { get; set; }
    
        public virtual SqlJob SqlJob { get; set; }
        public virtual ICollection<SqlJobStepIteration> SqlJobStepIterations { get; set; }
        public virtual Tool Tool { get; set; }
    }
}
