//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkypeIntlPortfolio.Fix
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SkypeIntlPortfolioContext : DbContext
    {
        public SkypeIntlPortfolioContext()
            : base("name=SkypeIntlPortfolioContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MilestoneCategory> MilestoneCategories { get; set; }
        public virtual DbSet<TestSchedule> TestSchedules { get; set; }
        public virtual DbSet<Release> Releases { get; set; }
        public virtual DbSet<Products_New> Products_New { get; set; }
    }
}
