//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocaLiz.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LocaLiz.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string AnswerNo {
            get {
                return ResourceManager.GetString("AnswerNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string AnswerYes {
            get {
                return ResourceManager.GetString("AnswerYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can provide you with strings to review in your native language and offer you the change to suggest better translations!.
        /// </summary>
        internal static string Capabilities {
            get {
                return ResourceManager.GetString("Capabilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry do not speak that language :(.
        /// </summary>
        internal static string Command_DoNotUnderstandLangauge {
            get {
                return ResourceManager.GetString("Command_DoNotUnderstandLangauge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In what language you would like to speak with me?.
        /// </summary>
        internal static string Command_In_What_Language {
            get {
                return ResourceManager.GetString("Command_In_What_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick one Language.
        /// </summary>
        internal static string Command_Select_One {
            get {
                return ResourceManager.GetString("Command_Select_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oki-doki-now switching to {0}.
        /// </summary>
        internal static string Command_SwtichToLanguage {
            get {
                return ResourceManager.GetString("Command_SwtichToLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey, my new Friend! Lets improve the localization quality of Skype!.
        /// </summary>
        internal static string ContactAdded {
            get {
                return ResourceManager.GetString("ContactAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to continue with evaluating translations?.
        /// </summary>
        internal static string ContinueWithEvaluations {
            get {
                return ResourceManager.GetString("ContinueWithEvaluations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string Discover_Female {
            get {
                return ResourceManager.GetString("Discover_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string Discover_Male {
            get {
                return ResourceManager.GetString("Discover_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string Discover_Other {
            get {
                return ResourceManager.GetString("Discover_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unspecified.
        /// </summary>
        internal static string Discover_Unspecified {
            get {
                return ResourceManager.GetString("Discover_Unspecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is your gender?.
        /// </summary>
        internal static string Discover_What_Gender {
            get {
                return ResourceManager.GetString("Discover_What_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I would like to learn more about you!.
        /// </summary>
        internal static string DiscoverUser {
            get {
                return ResourceManager.GetString("DiscoverUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So you are a master of the {1} language..
        /// </summary>
        internal static string DiscoverUserGoodReponse {
            get {
                return ResourceManager.GetString("DiscoverUserGoodReponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What are the languages, that you master at a very good level?.
        /// </summary>
        internal static string DiscoverUserLanguageGood {
            get {
                return ResourceManager.GetString("DiscoverUserLanguageGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is your native language?.
        /// </summary>
        internal static string DiscoverUserLanguageNative {
            get {
                return ResourceManager.GetString("DiscoverUserLanguageNative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From what I understood your native language is {0}..
        /// </summary>
        internal static string DiscoverUserNativeResponce {
            get {
                return ResourceManager.GetString("DiscoverUserNativeResponce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to judge the current translation quality between {0} and {1}?.
        /// </summary>
        internal static string DiscoverUserQualityJudge {
            get {
                return ResourceManager.GetString("DiscoverUserQualityJudge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please type-in your suggestion! And then press Enter (Send message).
        /// </summary>
        internal static string Evaluate_EnterSuggestion {
            get {
                return ResourceManager.GetString("Evaluate_EnterSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to evaluate some translation quality?.
        /// </summary>
        internal static string Evaluate_Init {
            get {
                return ResourceManager.GetString("Evaluate_Init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terrible. I can translate better!.
        /// </summary>
        internal static string EvaluateString_Bad_Action {
            get {
                return ResourceManager.GetString("EvaluateString_Bad_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excellent translation.
        /// </summary>
        internal static string EvaluateString_Best_Action {
            get {
                return ResourceManager.GetString("EvaluateString_Best_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is fine translation.
        /// </summary>
        internal static string EvaluateString_Medium_Action {
            get {
                return ResourceManager.GetString("EvaluateString_Medium_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluate a Translation from source &apos;{0}&apos;  | {1}.
        /// </summary>
        internal static string EvaluateString_Source {
            get {
                return ResourceManager.GetString("EvaluateString_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Meaning of Life, the Universe, and Everything.
        /// </summary>
        internal static string Hack42 {
            get {
                return ResourceManager.GetString("Hack42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please put a mark on translation quality (1-10, with 10 - the best and 1 - the worst) {0} language phrase &quot;{1}&quot; (id {2}) is translated as &quot;{3}&quot; in {4} language!.
        /// </summary>
        internal static string QualityCompareStrings {
            get {
                return ResourceManager.GetString("QualityCompareStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wow! That sounds great! We will give a cookie to the translators. Thank you!.
        /// </summary>
        internal static string QualityExcelent {
            get {
                return ResourceManager.GetString("QualityExcelent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is passable. Would you like to suggest something better?.
        /// </summary>
        internal static string QualityMedicore {
            get {
                return ResourceManager.GetString("QualityMedicore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouch, thats too bad. Can you suggest a better translation?.
        /// </summary>
        internal static string QualityYouCanBetter {
            get {
                return ResourceManager.GetString("QualityYouCanBetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for all the fish!.
        /// </summary>
        internal static string RemovedContact {
            get {
                return ResourceManager.GetString("RemovedContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string StatusReport {
            get {
                return ResourceManager.GetString("StatusReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have translated {0} and reviewed {1} language pairs.
        /// </summary>
        internal static string StatusReportAnswer {
            get {
                return ResourceManager.GetString("StatusReportAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have translated {0} and reviewed {1} language pairs. {2} of your translations are used in production! Good job!.
        /// </summary>
        internal static string StatusReportExtendedAnswer {
            get {
                return ResourceManager.GetString("StatusReportExtendedAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string String10 {
            get {
                return ResourceManager.GetString("String10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string String11 {
            get {
                return ResourceManager.GetString("String11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unspecified.
        /// </summary>
        internal static string String12 {
            get {
                return ResourceManager.GetString("String12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is your gender?.
        /// </summary>
        internal static string String13 {
            get {
                return ResourceManager.GetString("String13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I would like to learn more about you!.
        /// </summary>
        internal static string String14 {
            get {
                return ResourceManager.GetString("String14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So you are a master of the {1} language..
        /// </summary>
        internal static string String15 {
            get {
                return ResourceManager.GetString("String15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What are the languages, that you master at a very good level?.
        /// </summary>
        internal static string String16 {
            get {
                return ResourceManager.GetString("String16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is your native language?.
        /// </summary>
        internal static string String17 {
            get {
                return ResourceManager.GetString("String17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From what I understood your native language is {0}..
        /// </summary>
        internal static string String18 {
            get {
                return ResourceManager.GetString("String18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to judge the current translation quality between {0} and {1}?.
        /// </summary>
        internal static string String19 {
            get {
                return ResourceManager.GetString("String19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can provide you with strings to review in your native language and offer you the change to suggest better translations!.
        /// </summary>
        internal static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please type-in your suggestion! And then press Enter (Send message).
        /// </summary>
        internal static string String20 {
            get {
                return ResourceManager.GetString("String20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to evaluate some translation quality?.
        /// </summary>
        internal static string String21 {
            get {
                return ResourceManager.GetString("String21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terrible. I can translate better!.
        /// </summary>
        internal static string String22 {
            get {
                return ResourceManager.GetString("String22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excellent translation.
        /// </summary>
        internal static string String23 {
            get {
                return ResourceManager.GetString("String23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is fine translation.
        /// </summary>
        internal static string String24 {
            get {
                return ResourceManager.GetString("String24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluate a Translation from source &apos;{0}&apos;  | {1}.
        /// </summary>
        internal static string String25 {
            get {
                return ResourceManager.GetString("String25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Meaning of Life, the Universe, and Everything.
        /// </summary>
        internal static string String26 {
            get {
                return ResourceManager.GetString("String26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please put a mark on translation quality (1-10, with 10 - the best and 1 - the worst) {0} language phrase &quot;{1}&quot; (id {2}) is translated as &quot;{3}&quot; in {4} language!.
        /// </summary>
        internal static string String27 {
            get {
                return ResourceManager.GetString("String27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wow! That sounds great! We will give a cookie to the translators. Thank you!.
        /// </summary>
        internal static string String28 {
            get {
                return ResourceManager.GetString("String28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is passable. Would you like to suggest something better?.
        /// </summary>
        internal static string String29 {
            get {
                return ResourceManager.GetString("String29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry do not speak that language :(.
        /// </summary>
        internal static string String3 {
            get {
                return ResourceManager.GetString("String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouch, that&apos;s too bad. Can you suggest a better translation?.
        /// </summary>
        internal static string String30 {
            get {
                return ResourceManager.GetString("String30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for all the fish!.
        /// </summary>
        internal static string String31 {
            get {
                return ResourceManager.GetString("String31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string String32 {
            get {
                return ResourceManager.GetString("String32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have translated {0} and reviewed {1} language pairs.
        /// </summary>
        internal static string String33 {
            get {
                return ResourceManager.GetString("String33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have translated {0} and reviewed {1} language pairs. {2} of your translations are used in production! Good job!.
        /// </summary>
        internal static string String34 {
            get {
                return ResourceManager.GetString("String34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you, your contribution will make a better user experience for you and other users!.
        /// </summary>
        internal static string String35 {
            get {
                return ResourceManager.GetString("String35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey, new friend! I am LocaLiz. You help me with giving feedback on translation quality..
        /// </summary>
        internal static string String36 {
            get {
                return ResourceManager.GetString("String36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In what language you would like to speak with me?.
        /// </summary>
        internal static string String4 {
            get {
                return ResourceManager.GetString("String4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick one Language.
        /// </summary>
        internal static string String5 {
            get {
                return ResourceManager.GetString("String5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oki-doki-now switching to {0}.
        /// </summary>
        internal static string String6 {
            get {
                return ResourceManager.GetString("String6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey, my new Friend! Lets improve the localization quality of Skype!.
        /// </summary>
        internal static string String7 {
            get {
                return ResourceManager.GetString("String7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to continue with evaluating translations?.
        /// </summary>
        internal static string String8 {
            get {
                return ResourceManager.GetString("String8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string String9 {
            get {
                return ResourceManager.GetString("String9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you, your contribution will make a better user experience for you and other users!.
        /// </summary>
        internal static string ThankYou {
            get {
                return ResourceManager.GetString("ThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey, new friend! I am LocaLiz. You help me with giving feedback on translation quality. .
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
    }
}
