#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ContextGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using SkypeIntlPortfolio.Data;

namespace SkypeIntlPortfolio.Data	
{
	public partial class EOLandProductsEntities : OpenAccessContext, IEOLandProductsEntitiesUnitOfWork
	{
		private static string connectionStringName = @"EOLandProductsConnection";
			
		private static BackendConfiguration backend = GetBackendConfiguration();
				
		private static MetadataSource metadataSource = XmlMetadataSource.FromAssemblyResource("EOLandProducts.rlinq");
		
		public EOLandProductsEntities()
			:base(connectionStringName, backend, metadataSource)
		{ }
		
		public EOLandProductsEntities(string connection)
			:base(connection, backend, metadataSource)
		{ }
		
		public EOLandProductsEntities(BackendConfiguration backendConfiguration)
			:base(connectionStringName, backendConfiguration, metadataSource)
		{ }
			
		public EOLandProductsEntities(string connection, MetadataSource metadataSource)
			:base(connection, backend, metadataSource)
		{ }
		
		public EOLandProductsEntities(string connection, BackendConfiguration backendConfiguration, MetadataSource metadataSource)
			:base(connection, backendConfiguration, metadataSource)
		{ }
			
		public IQueryable<FabricOnboarding> FabricOnboardings 
		{
			get
			{
				return this.GetAll<FabricOnboarding>();
			}
		}
		
		public IQueryable<FabricOnboardingsLowLevelStatus> FabricOnboardingsLowLevelStatus 
		{
			get
			{
				return this.GetAll<FabricOnboardingsLowLevelStatus>();
			}
		}
		
		public IQueryable<FabricOnboardingsHighLevelStatus> FabricOnboardingsHighLevelStatus 
		{
			get
			{
				return this.GetAll<FabricOnboardingsHighLevelStatus>();
			}
		}
		
		public static BackendConfiguration GetBackendConfiguration()
		{
			BackendConfiguration backend = new BackendConfiguration();
			backend.Backend = "MsSql";
			backend.ProviderName = "System.Data.SqlClient";
		
			CustomizeBackendConfiguration(ref backend);
		
			return backend;
		}
		
		/// <summary>
		/// Allows you to customize the BackendConfiguration of EOLandProductsEntities.
		/// </summary>
		/// <param name="config">The BackendConfiguration of EOLandProductsEntities.</param>
		static partial void CustomizeBackendConfiguration(ref BackendConfiguration config);
		
	}
	
	public interface IEOLandProductsEntitiesUnitOfWork : IUnitOfWork
	{
		IQueryable<FabricOnboarding> FabricOnboardings
		{
			get;
		}
		IQueryable<FabricOnboardingsLowLevelStatus> FabricOnboardingsLowLevelStatus
		{
			get;
		}
		IQueryable<FabricOnboardingsHighLevelStatus> FabricOnboardingsHighLevelStatus
		{
			get;
		}
	}
}
#pragma warning restore 1591
