#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using SkypeIntlPortfolio.Data;

namespace SkypeIntlPortfolio.Data	
{
	public partial class FabricOnboarding
	{
		private string _jiraPBI;
		public virtual string JiraPBI
		{
			get
			{
				return this._jiraPBI;
			}
			set
			{
				this._jiraPBI = value;
			}
		}
		
		private int _iD;
		public virtual int ID
		{
			get
			{
				return this._iD;
			}
			set
			{
				this._iD = value;
			}
		}
		
		private string _summary;
		public virtual string Summary
		{
			get
			{
				return this._summary;
			}
			set
			{
				this._summary = value;
			}
		}
		
		private string _epicLabels;
		public virtual string EpicLabels
		{
			get
			{
				return this._epicLabels;
			}
			set
			{
				this._epicLabels = value;
			}
		}
		
		private string _labels;
		public virtual string Labels
		{
			get
			{
				return this._labels;
			}
			set
			{
				this._labels = value;
			}
		}
		
		private string _status;
		public virtual string Status
		{
			get
			{
				return this._status;
			}
			set
			{
				this._status = value;
			}
		}
		
		private string _sprint;
		public virtual string Sprint
		{
			get
			{
				return this._sprint;
			}
			set
			{
				this._sprint = value;
			}
		}
		
		private string _links;
		public virtual string Links
		{
			get
			{
				return this._links;
			}
			set
			{
				this._links = value;
			}
		}
		
		private int? _parentOnboardingTaskID;
		public virtual int? ParentOnboardingTaskID
		{
			get
			{
				return this._parentOnboardingTaskID;
			}
			set
			{
				this._parentOnboardingTaskID = value;
			}
		}
		
		private DateTime? _createdDate;
		public virtual DateTime? CreatedDate
		{
			get
			{
				return this._createdDate;
			}
			set
			{
				this._createdDate = value;
			}
		}
		
		private DateTime? _closedDate;
		public virtual DateTime? ClosedDate
		{
			get
			{
				return this._closedDate;
			}
			set
			{
				this._closedDate = value;
			}
		}
		
		private FabricOnboarding _fabricOnboarding1;
		public virtual FabricOnboarding FabricOnboardingParent
		{
			get
			{
				return this._fabricOnboarding1;
			}
			set
			{
				this._fabricOnboarding1 = value;
			}
		}
		
		private IList<FabricOnboarding> _fabricOnboardings = new List<FabricOnboarding>();
		public virtual IList<FabricOnboarding> FabricOnboardings
		{
			get
			{
				return this._fabricOnboardings;
			}
		}
		
	}
}
#pragma warning restore 1591
