#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace SkypeIntlPortfolio.Data	
{
	public partial class FabricOnboardingsHighLevelStatus
	{
		private string _project;
		public virtual string Project
		{
			get
			{
				return this._project;
			}
			set
			{
				this._project = value;
			}
		}
		
		private string _phase;
		public virtual string Phase
		{
			get
			{
				return this._phase;
			}
			set
			{
				this._phase = value;
			}
		}
		
	}
}
#pragma warning restore 1591
