// Code is generated by Telerik Data Access Service Wizard
// using WebApiRepositories.tt template

using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Http;
using Telerik.OpenAccess;
using SkypeIntlPortfolio.Data;

namespace SkypeIntlPortfolio
{
	public partial class FabricOnboardingRepository : OpenAccessBaseRepository<SkypeIntlPortfolio.Data.FabricOnboarding, SkypeIntlPortfolio.Data.EOLandProductsEntities>
    {
	
    }

	public partial class FabricOnboardingsHighLevelStatusRepository : OpenAccessBaseRepository<SkypeIntlPortfolio.Data.FabricOnboardingsHighLevelStatus, SkypeIntlPortfolio.Data.EOLandProductsEntities>
    {
	
    }

	public partial class FabricOnboardingsLowLevelStatusRepository : OpenAccessBaseRepository<SkypeIntlPortfolio.Data.FabricOnboardingsLowLevelStatus, SkypeIntlPortfolio.Data.EOLandProductsEntities>
    {
	
    }

}
