//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkypeIntlPortfolio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Products1 = new HashSet<Product>();
        }
    
        public int ID { get; set; }
        public string Product1 { get; set; }
        public int ProductGroupKey { get; set; }
        public int ProductUserTypeKey { get; set; }
        public int ProductStatusKey { get; set; }
        public Nullable<int> ParentProjectKey { get; set; }
        public int ProductTypeKey { get; set; }
        public Nullable<int> FabricOnboardingProjectKey { get; set; }
        public string ProductStudioLink { get; set; }
    
        public virtual ICollection<Product> Products1 { get; set; }
        public virtual Product Product2 { get; set; }
    }
}
