//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkypeIntlPortfolio.Ajax
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasicLanguageList
    {
        public BasicLanguageList()
        {
            this.SpokenInputOutputs = new HashSet<SpokenInputOutput>();
            this.TextInputOutputs = new HashSet<TextInputOutput>();
            this.ResourceFiles_Target = new HashSet<ResourceFiles_Target>();
            this.UILanguages = new HashSet<UILanguage>();
            this.UALanguages = new HashSet<UALanguage>();
        }
    
        public int LanguageKey { get; set; }
        public string Language { get; set; }
        public string CultureName { get; set; }
    
        public virtual ICollection<SpokenInputOutput> SpokenInputOutputs { get; set; }
        public virtual ICollection<TextInputOutput> TextInputOutputs { get; set; }
        public virtual ICollection<ResourceFiles_Target> ResourceFiles_Target { get; set; }
        public virtual ICollection<UILanguage> UILanguages { get; set; }
        public virtual ICollection<UALanguage> UALanguages { get; set; }
    }
}
