//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkypeIntlPortfolio.Ajax
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        public Branch()
        {
            this.stringData_LCTImportData = new HashSet<stringData_LCTImportData>();
        }
    
        public int BranchID { get; set; }
        public string Branch_Name { get; set; }
        public int ProductKey { get; set; }
    
        public virtual ICollection<stringData_LCTImportData> stringData_LCTImportData { get; set; }
        public virtual Products_New Products_New { get; set; }
    }
}
