//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkypeIntlPortfolio.Ajax
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuildRequest
    {
        public string RequestID { get; set; }
        public string BuildType { get; set; }
        public string SourcePath { get; set; }
        public string FromBuildVersion { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> BranchID { get; set; }
        public string BranchName { get; set; }
        public string Tenant { get; set; }
        public string SkypeLctFilePaths { get; set; }
        public string LyncServerComponentList { get; set; }
        public Nullable<bool> IsComponentListAll { get; set; }
        public Nullable<int> BuildToKeep { get; set; }
        public string DestinationPath { get; set; }
    }
}
