//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkypeIntlPortfolio.Ajax
{
    using System;
    using System.Collections.Generic;
    
    public partial class EOL
    {
        public string llCC { get; set; }
        public int ProductKey { get; set; }
        public string Language_Name { get; set; }
        public string Language_Support_Level { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
