//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkypeIntlPortfolio.Ajax
{
    using System;
    using System.Collections.Generic;
    
    public partial class FabricTenant
    {
        public FabricTenant()
        {
            this.ResourceFiles = new HashSet<ResourceFile>();
        }
    
        public int TenantKey { get; set; }
        public string Fabric_Tenant { get; set; }
    
        public virtual ICollection<ResourceFile> ResourceFiles { get; set; }
    }
}
