//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkypeIntlPortfolio.Ajax
{
    using System;
    using System.Collections.Generic;
    
    public partial class FabricOnboarding
    {
        public FabricOnboarding()
        {
            this.FabricOnboarding1 = new HashSet<FabricOnboarding>();
        }
    
        public int OnboardingID { get; set; }
        public int ProductKey { get; set; }
        public string JiraPBI { get; set; }
        public string Summary { get; set; }
        public string EpicLabel { get; set; }
        public string Label { get; set; }
        public string PBI_Status { get; set; }
        public string Links { get; set; }
        public Nullable<int> ParentOnboardingID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
        public string Sprint { get; set; }
    
        public virtual ICollection<FabricOnboarding> FabricOnboarding1 { get; set; }
        public virtual FabricOnboarding FabricOnboarding2 { get; set; }
    }
}
