//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkypeIntlPortfolio.Ajax
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feature
    {
        public Feature()
        {
            this.SpokenInputOutputs = new HashSet<SpokenInputOutput>();
            this.TextInputOutputs = new HashSet<TextInputOutput>();
        }
    
        public int FeatureKey { get; set; }
        public string FeatureName { get; set; }
        public Nullable<int> ProductKey { get; set; }
    
        public virtual ICollection<SpokenInputOutput> SpokenInputOutputs { get; set; }
        public virtual ICollection<TextInputOutput> TextInputOutputs { get; set; }
        public virtual Products_New Products_New { get; set; }
    }
}
