//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkypeIntlPortfolio.Ajax
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryResourceFile
    {
        public int FileKey { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public Nullable<bool> Deleted { get; set; }
    
        public virtual ResourceFile ResourceFile { get; set; }
    }
}
