//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkypeIntlPortfolio.Ajax
{
    using System;
    using System.Collections.Generic;
    
    public partial class Milestone
    {
        public int ProductKey { get; set; }
        public int ReleaseKey { get; set; }
        public int MilestoneKey { get; set; }
        public string Milestone_Name { get; set; }
        public Nullable<System.DateTime> Milestone_Start_Date { get; set; }
        public Nullable<System.DateTime> Milestone_End_Date { get; set; }
        public string Line_of_Sight { get; set; }
        public int MilestoneCategoryKey { get; set; }
        public string Milestone_Assigned_To { get; set; }
        public string Vso_Web_Url { get; set; }
        public string Vso_Api_Url { get; set; }
    
        public virtual MilestoneCategory MilestoneCategory { get; set; }
        public virtual Product Product { get; set; }
        public virtual Release Release { get; set; }
    }
}
