//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkypeIntlPortfolio.Ajax
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SkypeIntlMonitoringEntities : DbContext
    {
        public SkypeIntlMonitoringEntities()
            : base("name=SkypeIntlMonitoringEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<vw_ProjectBuildInfo> vw_ProjectBuildInfo { get; set; }
        public virtual DbSet<vw_ProjectFamilyInfo> vw_ProjectFamilyInfo { get; set; }
        public virtual DbSet<RemoteLogger> RemoteLoggers { get; set; }
        public virtual DbSet<RemoteStateLogger> RemoteStateLoggers { get; set; }
        public virtual DbSet<vw_ToolsJobsStepsInfo> vw_ToolsJobsStepsInfo { get; set; }
        public virtual DbSet<vw_GetJobExecutionView> vw_GetJobExecutionView { get; set; }
        public virtual DbSet<New_SqlJobs> New_SqlJobs { get; set; }
        public virtual DbSet<RemoteStateLoggerImage> RemoteStateLoggerImages { get; set; }
    
        [DbFunction("SkypeIntlMonitoringEntities", "Fn_New_GetJobListForHistory")]
        public virtual IQueryable<Fn_New_GetJobListForHistory_Result> Fn_New_GetJobListForHistory(Nullable<System.DateTime> fromDate, Nullable<System.DateTime> endDate)
        {
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("fromDate", fromDate) :
                new ObjectParameter("fromDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("endDate", endDate) :
                new ObjectParameter("endDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Fn_New_GetJobListForHistory_Result>("[SkypeIntlMonitoringEntities].[Fn_New_GetJobListForHistory](@fromDate, @endDate)", fromDateParameter, endDateParameter);
        }
    
        [DbFunction("SkypeIntlMonitoringEntities", "Fn_New_GetJobsExecution")]
        public virtual IQueryable<Fn_New_GetJobsExecution_Result> Fn_New_GetJobsExecution(string jobName, Nullable<System.DateTime> fromDate, Nullable<System.DateTime> endDate)
        {
            var jobNameParameter = jobName != null ?
                new ObjectParameter("jobName", jobName) :
                new ObjectParameter("jobName", typeof(string));
    
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("fromDate", fromDate) :
                new ObjectParameter("fromDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("endDate", endDate) :
                new ObjectParameter("endDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Fn_New_GetJobsExecution_Result>("[SkypeIntlMonitoringEntities].[Fn_New_GetJobsExecution](@jobName, @fromDate, @endDate)", jobNameParameter, fromDateParameter, endDateParameter);
        }
    
        [DbFunction("SkypeIntlMonitoringEntities", "Fn_New_GetJobsLatestStatus")]
        public virtual IQueryable<Fn_New_GetJobsLatestStatus_Result> Fn_New_GetJobsLatestStatus(Nullable<System.DateTime> fromDate, Nullable<System.DateTime> endDate)
        {
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("fromDate", fromDate) :
                new ObjectParameter("fromDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("endDate", endDate) :
                new ObjectParameter("endDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Fn_New_GetJobsLatestStatus_Result>("[SkypeIntlMonitoringEntities].[Fn_New_GetJobsLatestStatus](@fromDate, @endDate)", fromDateParameter, endDateParameter);
        }
    
        [DbFunction("SkypeIntlMonitoringEntities", "Fn_New_GetJobStepsforExecution")]
        public virtual IQueryable<Fn_New_GetJobStepsforExecution_Result> Fn_New_GetJobStepsforExecution(string jobName, Nullable<int> jobInstanceId, Nullable<System.DateTime> jobStartTime)
        {
            var jobNameParameter = jobName != null ?
                new ObjectParameter("jobName", jobName) :
                new ObjectParameter("jobName", typeof(string));
    
            var jobInstanceIdParameter = jobInstanceId.HasValue ?
                new ObjectParameter("jobInstanceId", jobInstanceId) :
                new ObjectParameter("jobInstanceId", typeof(int));
    
            var jobStartTimeParameter = jobStartTime.HasValue ?
                new ObjectParameter("jobStartTime", jobStartTime) :
                new ObjectParameter("jobStartTime", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Fn_New_GetJobStepsforExecution_Result>("[SkypeIntlMonitoringEntities].[Fn_New_GetJobStepsforExecution](@jobName, @jobInstanceId, @jobStartTime)", jobNameParameter, jobInstanceIdParameter, jobStartTimeParameter);
        }
    
        [DbFunction("SkypeIntlMonitoringEntities", "Fn_New_GetJobStepsForNotification")]
        public virtual IQueryable<Fn_New_GetJobStepsForNotification_Result> Fn_New_GetJobStepsForNotification(Nullable<int> lastNotificationJobInstanceId)
        {
            var lastNotificationJobInstanceIdParameter = lastNotificationJobInstanceId.HasValue ?
                new ObjectParameter("LastNotificationJobInstanceId", lastNotificationJobInstanceId) :
                new ObjectParameter("LastNotificationJobInstanceId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Fn_New_GetJobStepsForNotification_Result>("[SkypeIntlMonitoringEntities].[Fn_New_GetJobStepsForNotification](@LastNotificationJobInstanceId)", lastNotificationJobInstanceIdParameter);
        }
    
        [DbFunction("SkypeIntlMonitoringEntities", "Fn_New_GetRunningJobs")]
        public virtual IQueryable<Fn_New_GetRunningJobs_Result> Fn_New_GetRunningJobs()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Fn_New_GetRunningJobs_Result>("[SkypeIntlMonitoringEntities].[Fn_New_GetRunningJobs]()");
        }
    
        [DbFunction("SkypeIntlMonitoringEntities", "Fn_New_GetServerTime")]
        public virtual IQueryable<Nullable<System.DateTime>> Fn_New_GetServerTime()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Nullable<System.DateTime>>("[SkypeIntlMonitoringEntities].[Fn_New_GetServerTime]()");
        }
    
        [DbFunction("SkypeIntlMonitoringEntities", "Fn_New_GetStepInPeriod")]
        public virtual IQueryable<Fn_New_GetStepInPeriod_Result> Fn_New_GetStepInPeriod(Nullable<int> periodTime_Minutes)
        {
            var periodTime_MinutesParameter = periodTime_Minutes.HasValue ?
                new ObjectParameter("PeriodTime_Minutes", periodTime_Minutes) :
                new ObjectParameter("PeriodTime_Minutes", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Fn_New_GetStepInPeriod_Result>("[SkypeIntlMonitoringEntities].[Fn_New_GetStepInPeriod](@PeriodTime_Minutes)", periodTime_MinutesParameter);
        }
    
        [DbFunction("SkypeIntlMonitoringEntities", "Fn_New_GetStepForRunningJob")]
        public virtual IQueryable<Fn_New_GetStepForRunningJob_Result> Fn_New_GetStepForRunningJob(string jobName)
        {
            var jobNameParameter = jobName != null ?
                new ObjectParameter("JobName", jobName) :
                new ObjectParameter("JobName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Fn_New_GetStepForRunningJob_Result>("[SkypeIntlMonitoringEntities].[Fn_New_GetStepForRunningJob](@JobName)", jobNameParameter);
        }
    }
}
