//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkypeIntlPortfolio.Ajax
{
    using System;
    using System.Collections.Generic;
    
    public partial class Platform
    {
        public Platform()
        {
            this.Products_New = new HashSet<Products_New>();
        }
    
        public int PlatformKey { get; set; }
        public string Platform1 { get; set; }
    
        public virtual ICollection<Products_New> Products_New { get; set; }
    }
}
