//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkypeIntlPortfolio.Ajax
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.EOLs = new HashSet<EOL>();
            this.Milestones = new HashSet<Milestone>();
            this.TestSchedules = new HashSet<TestSchedule>();
        }
    
        public int ProductKey { get; set; }
        public string Product_Name { get; set; }
        public string Product_Description { get; set; }
        public string Family { get; set; }
        public string User_Type { get; set; }
        public string Product_Type { get; set; }
        public string Product_Status { get; set; }
        public string ProductStudioLink { get; set; }
        public string Fabric_Status { get; set; }
        public string Fabric_Onboarding_EpicLabel { get; set; }
        public string Loc_PM_Alias { get; set; }
        public string Loc_PM_Location { get; set; }
        public string Core_Team_s_Location { get; set; }
        public string Resource_File_Path { get; set; }
        public string Core_Team_Contacts { get; set; }
    
        public virtual ICollection<EOL> EOLs { get; set; }
        public virtual ICollection<Milestone> Milestones { get; set; }
        public virtual ICollection<TestSchedule> TestSchedules { get; set; }
    }
}
