//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkypeIntlPortfolio.Ajax
{
    using System;
    using System.Collections.Generic;
    
    public partial class Release
    {
        public Release()
        {
            this.Milestones = new HashSet<Milestone>();
            this.TestSchedules = new HashSet<TestSchedule>();
        }
    
        public int ProductKey { get; set; }
        public int VSO_ID { get; set; }
        public string VSO_Title { get; set; }
        public string VSO_Type { get; set; }
        public string VSO_Status { get; set; }
        public System.DateTime VSO_LocStartDate { get; set; }
        public System.DateTime VSO_DueDate { get; set; }
        public string VSO_Assigned_To { get; set; }
        public string VSO_Family { get; set; }
        public string VSO_IterationPath { get; set; }
        public string VSO_AreaPath { get; set; }
        public System.DateTime VSO_ChangedDate { get; set; }
        public string VSO_ProductName { get; set; }
        public string VSO_Url { get; set; }
        public bool Deleted { get; set; }
        public string VSO_Tags { get; set; }
    
        public virtual ICollection<Milestone> Milestones { get; set; }
        public virtual ICollection<TestSchedule> TestSchedules { get; set; }
        public virtual Products_New Products_New { get; set; }
    }
}
