//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkypeIntlPortfolio.Ajax
{
    using System;
    using System.Collections.Generic;
    
    public partial class RemoteLogger
    {
        public int Id { get; set; }
        public string ApplicationName { get; set; }
        public string Exception { get; set; }
        public string ExceptionStackTrace { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string UserIdentity { get; set; }
        public string BatchID { get; set; }
        public Nullable<int> StateID { get; set; }
    }
}
