//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkypeIntlPortfolio.Ajax
{
    using System;
    using System.Collections.Generic;
    
    public partial class RemoteStateLogger
    {
        public RemoteStateLogger()
        {
            this.RemoteStateLoggerImages = new HashSet<RemoteStateLoggerImage>();
        }
    
        public int Id { get; set; }
        public string TestcaseName { get; set; }
        public string LanguageName { get; set; }
        public bool State { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string ApplicationName { get; set; }
        public string BatchID { get; set; }
        public string UserIdentity { get; set; }
        public System.DateTime StartDate { get; set; }
    
        public virtual ICollection<RemoteStateLoggerImage> RemoteStateLoggerImages { get; set; }
    }
}
