//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkypeIntlPortfolio.Ajax
{
    using System;
    using System.Collections.Generic;
    
    public partial class RemoteStateLoggerImage
    {
        public int Id { get; set; }
        public int RemoteStateLoggerID { get; set; }
        public string ImagePath { get; set; }
    
        public virtual RemoteStateLogger RemoteStateLogger { get; set; }
    }
}
