//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkypeIntlPortfolio.Ajax
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResourceFile
    {
        public ResourceFile()
        {
            this.HistoryResourceFiles = new HashSet<HistoryResourceFile>();
            this.ResourceFiles_Target = new HashSet<ResourceFiles_Target>();
            this.UILanguages = new HashSet<UILanguage>();
            this.Products_New = new HashSet<Products_New>();
            this.UALanguages = new HashSet<UALanguage>();
        }
    
        public int FileKey { get; set; }
        public string File_Name { get; set; }
        public string File_Type { get; set; }
        public string LCG_File_Location { get; set; }
        public string Fabric_Project { get; set; }
        public Nullable<int> FabricTenantKey { get; set; }
        public string Source_File_Location { get; set; }
        public Nullable<int> ParserID { get; set; }
        public string RepoURL { get; set; }
        public string repoBranch { get; set; }
        public string repoType { get; set; }
    
        public virtual FabricTenant FabricTenant { get; set; }
        public virtual ICollection<HistoryResourceFile> HistoryResourceFiles { get; set; }
        public virtual ICollection<ResourceFiles_Target> ResourceFiles_Target { get; set; }
        public virtual ICollection<UILanguage> UILanguages { get; set; }
        public virtual ICollection<Products_New> Products_New { get; set; }
        public virtual ICollection<UALanguage> UALanguages { get; set; }
    }
}
