//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkypeIntlPortfolio.Ajax
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResourceFiles_Target
    {
        public ResourceFiles_Target()
        {
            this.stringData_TargetRepoData = new HashSet<stringData_TargetRepoData>();
            this.HistoryResourceFiles_Target = new HashSet<HistoryResourceFiles_Target>();
        }
    
        public int SourceFileKey { get; set; }
        public int TargetFileKey { get; set; }
        public int LanguageKey { get; set; }
        public string File_Name { get; set; }
        public string Target_File_Location { get; set; }
        public string RepoURL { get; set; }
        public string repoBranch { get; set; }
        public string repoType { get; set; }
        public Nullable<int> Number_of_Strings__Fabric_ { get; set; }
    
        public virtual BasicLanguageList BasicLanguageList { get; set; }
        public virtual ICollection<stringData_TargetRepoData> stringData_TargetRepoData { get; set; }
        public virtual ICollection<HistoryResourceFiles_Target> HistoryResourceFiles_Target { get; set; }
        public virtual ResourceFile ResourceFile { get; set; }
    }
}
