//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkypeIntlPortfolio.Ajax
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpokenInputOutput
    {
        public int SpokenInputOutputKey { get; set; }
        public Nullable<int> FeatureKey { get; set; }
        public Nullable<int> LanguageKey { get; set; }
        public Nullable<bool> Spoken_Input { get; set; }
        public Nullable<bool> Spoken_Output { get; set; }
        public string Comments { get; set; }
    
        public virtual BasicLanguageList BasicLanguageList { get; set; }
        public virtual Feature Feature { get; set; }
    }
}
