//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkypeIntlPortfolio.Ajax
{
    using System;
    using System.Collections.Generic;
    
    public partial class stringData_LCTImportData
    {
        public int ResourceIDKey { get; set; }
        public int BranchID { get; set; }
        public string Translation { get; set; }
        public string Culture { get; set; }
        public Nullable<int> ResourceOrigin { get; set; }
        public Nullable<System.DateTime> ResourcesUpdatedDate { get; set; }
        public string StringCategory { get; set; }
        public string TermNote { get; set; }
        public string LocStatus { get; set; }
        public string TransOrigin { get; set; }
        public string Instructions { get; set; }
        public string EnglishValue { get; set; }
        public Nullable<bool> UsrLk { get; set; }
        public Nullable<bool> DevLk { get; set; }
        public bool Locked { get; set; }
        public int WordCount { get; set; }
        public string oResourcesDB { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual stringData_MasterResourceList stringData_MasterResourceList { get; set; }
    }
}
