//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkypeIntlPortfolio.Ajax
{
    using System;
    using System.Collections.Generic;
    
    public partial class stringData_MasterResourceList
    {
        public stringData_MasterResourceList()
        {
            this.stringData_BuildData = new HashSet<stringData_BuildData>();
            this.stringData_LCTImportData = new HashSet<stringData_LCTImportData>();
            this.stringData_SourceRepoData = new HashSet<stringData_SourceRepoData>();
            this.stringData_TargetRepoData = new HashSet<stringData_TargetRepoData>();
        }
    
        public int ResourceIDkey { get; set; }
        public int ResourceFileKey { get; set; }
        public string Parser_Identifier { get; set; }
    
        public virtual ICollection<stringData_BuildData> stringData_BuildData { get; set; }
        public virtual ICollection<stringData_LCTImportData> stringData_LCTImportData { get; set; }
        public virtual ICollection<stringData_SourceRepoData> stringData_SourceRepoData { get; set; }
        public virtual ICollection<stringData_TargetRepoData> stringData_TargetRepoData { get; set; }
    }
}
