//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkypeIntlPortfolio.Ajax
{
    using System;
    using System.Collections.Generic;
    
    public partial class stringData_TargetRepoData
    {
        public int ResourceIDKey { get; set; }
        public string Target_Translation { get; set; }
        public System.DateTime ResourceUpdateDate { get; set; }
        public int BranchID { get; set; }
        public bool Deleted { get; set; }
        public int TargetFileKey { get; set; }
    
        public virtual ResourceFiles_Target ResourceFiles_Target { get; set; }
        public virtual stringData_MasterResourceList stringData_MasterResourceList { get; set; }
    }
}
