//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkypeIntlPortfolio.Ajax
{
    using System;
    using System.Collections.Generic;
    
    public partial class stringData_BuildData
    {
        public int ResourceIDKey { get; set; }
        public int BranchID { get; set; }
        public string Culture { get; set; }
        public string String_Value { get; set; }
        public string Build { get; set; }
        public Nullable<System.DateTime> Build_Date { get; set; }
    
        public virtual stringData_MasterResourceList stringData_MasterResourceList { get; set; }
    }
}
