//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkypeIntlPortfolio.Ajax
{
    using System;
    using System.Collections.Generic;
    
    public partial class suppData_EngineeringInfo
    {
        public string Ops_Owner { get; set; }
        public string Location_Owned_in { get; set; }
        public string Core_team_location { get; set; }
        public string Source_Control { get; set; }
        public string Source_Storage { get; set; }
        public string File_Formats { get; set; }
        public string Intl_Build_Process { get; set; }
        public int ProductKey { get; set; }
    }
}
