//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkypeIntlPortfolio.Ajax
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test_Pass
    {
        public int ProductKey { get; set; }
        public int ReleaseKey { get; set; }
        public int TestPassKey { get; set; }
        public string Test_Pass_Name { get; set; }
        public Nullable<System.DateTime> Test_Pass_Start { get; set; }
        public Nullable<System.DateTime> Test_Pass_End { get; set; }
        public bool Deleted { get; set; }
    }
}
