//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkypeIntlPortfolio.Ajax
{
    using System;
    using System.Collections.Generic;
    
    public partial class UAQuality
    {
        public UAQuality()
        {
            this.UALanguages = new HashSet<UALanguage>();
        }
    
        public int QualityID { get; set; }
        public string QualityName { get; set; }
    
        public virtual ICollection<UALanguage> UALanguages { get; set; }
    }
}
