//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkypeIntlPortfolio.Ajax
{
    using System;
    using System.Collections.Generic;
    
    public partial class UIVacationCategory
    {
        public UIVacationCategory()
        {
            this.VacationInfoes = new HashSet<VacationInfo>();
        }
    
        public int UICategoryID { get; set; }
        public string UIVacationCategory1 { get; set; }
    
        public virtual ICollection<VacationInfo> VacationInfoes { get; set; }
    }
}
