//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkypeIntlPortfolio.Ajax
{
    using System;
    using System.Collections.Generic;
    
    public partial class vm_vsoTaskInfo
    {
        public string Key { get; set; }
        public int Epic_ID { get; set; }
        public Nullable<long> ES_ID { get; set; }
        public string ES_Title { get; set; }
        public string ES_Tag { get; set; }
        public Nullable<double> VsoItemHours_Sum { get; set; }
    }
}
