//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkypeIntlPortfolio.Ajax
{
    using System;
    using System.Collections.Generic;
    
    public partial class VSoWorkItem
    {
        public int ID { get; set; }
        public string VSO_Title { get; set; }
        public string VSO_Type { get; set; }
        public string VSO_ProductName { get; set; }
        public string VSO_IterationPath { get; set; }
        public string VSO_AreaPath { get; set; }
        public string VSO_Family { get; set; }
        public System.DateTime VSO_StartDate { get; set; }
        public System.DateTime VSO_DueDate { get; set; }
        public System.DateTime VSO_ChangedDate { get; set; }
        public int ProductKey { get; set; }
        public string VSO_Assigned_To { get; set; }
    }
}
