//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkypeIntlPortfolio.Ajax
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_MilestoneInfo
    {
        public int RowID { get; set; }
        public string Product_Name { get; set; }
        public int ProductKey { get; set; }
        public string Family { get; set; }
        public string User_Type { get; set; }
        public string Product_Description { get; set; }
        public string Fabric_Onboarding_EpicLabel { get; set; }
        public string Fabric_Status { get; set; }
        public string Loc_PM_Alias { get; set; }
        public string Core_Team_s_Location { get; set; }
        public string Loc_PM_Location { get; set; }
        public string Resource_File_Path { get; set; }
        public string Core_Team_Contacts { get; set; }
        public string Release_Title { get; set; }
        public Nullable<int> Release_ID { get; set; }
        public Nullable<System.DateTime> Release_LocStartDate { get; set; }
        public Nullable<System.DateTime> Release_DueDate { get; set; }
        public string Release_Assigned_To { get; set; }
        public string Release_Url { get; set; }
        public Nullable<int> MilestoneKey { get; set; }
        public string Milestone_Name { get; set; }
        public Nullable<System.DateTime> Milestone_Start_Date { get; set; }
        public Nullable<System.DateTime> Milestone_End_Date { get; set; }
        public string Line_of_Sight { get; set; }
        public Nullable<int> MilestoneCategoryKey { get; set; }
        public string Milestone_Assigned_To { get; set; }
        public string Milestone_Category_Name { get; set; }
    }
}
