//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkypeIntlPortfolio.Ajax
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_OfficialMilestoneDates
    {
        public int ReleaseKey { get; set; }
        public string Milestone_Category_Name { get; set; }
        public Nullable<System.DateTime> Milestone_Start_Date { get; set; }
        public Nullable<System.DateTime> Milestone_End_Date { get; set; }
    }
}
