//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkypeIntlPortfolio.Ajax
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ProjectBuildInfo
    {
        public int BranchID { get; set; }
        public int ProjectID { get; set; }
        public string BuildVersion { get; set; }
        public string BranchIdentity { get; set; }
        public string PDName { get; set; }
        public string PDLinks { get; set; }
        public bool IsVisible { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
    }
}
