//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkypeIntlPortfolio.Ajax
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ToolsJobsStepsInfo
    {
        public string Tool_Name { get; set; }
        public string Job_Name { get; set; }
        public string Step_Name { get; set; }
    }
}
