//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkypeIntlMonitoring.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobRunStatus
    {
        public JobRunStatus()
        {
            this.SqlJobStepIterations = new HashSet<SqlJobStepIteration>();
            this.SqlJobs = new HashSet<SqlJob>();
        }
    
        public int Job_Run_Status_ID { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<SqlJobStepIteration> SqlJobStepIterations { get; set; }
        public virtual ICollection<SqlJob> SqlJobs { get; set; }
    }
}
