//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkypeIntlMonitoring.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SkypeIntlMonitoringContext : DbContext
    {
        public SkypeIntlMonitoringContext()
            : base("name=SkypeIntlMonitoringContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LogFile> LogFiles { get; set; }
        public virtual DbSet<SqlJob> SqlJobs { get; set; }
        public virtual DbSet<SqlJobStepIteration> SqlJobStepIterations { get; set; }
        public virtual DbSet<SqlJobStep> SqlJobSteps { get; set; }
        public virtual DbSet<Tool> Tools { get; set; }
        public virtual DbSet<SqlJobList> SqlJobLists { get; set; }
        public virtual DbSet<JobRunStatus> JobRunStatuses { get; set; }
        public virtual DbSet<ClientToolsDownload> ClientToolsDownloads { get; set; }
    
        public virtual int storedProc_Add_Update_SqlJobInfo(string sqlJobName)
        {
            var sqlJobNameParameter = sqlJobName != null ?
                new ObjectParameter("SqlJobName", sqlJobName) :
                new ObjectParameter("SqlJobName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("storedProc_Add_Update_SqlJobInfo", sqlJobNameParameter);
        }
    
        public virtual int storedProc_Add_Update_SqlJobStepInfo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("storedProc_Add_Update_SqlJobStepInfo");
        }
    
        public virtual int storedProc_Add_Update_SqlJobStepIteration()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("storedProc_Add_Update_SqlJobStepIteration");
        }
    
        [DbFunction("SkypeIntlMonitoringContext", "Fn_GetSQLJobIterationInfo")]
        public virtual IQueryable<Fn_GetSQLJobIterationInfo_Result1> Fn_GetSQLJobIterationInfo(string job_Name)
        {
            var job_NameParameter = job_Name != null ?
                new ObjectParameter("Job_Name", job_Name) :
                new ObjectParameter("Job_Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Fn_GetSQLJobIterationInfo_Result1>("[SkypeIntlMonitoringContext].[Fn_GetSQLJobIterationInfo](@Job_Name)", job_NameParameter);
        }
    
        [DbFunction("SkypeIntlMonitoringContext", "Fn_GetSQLJobStepInfo")]
        public virtual IQueryable<Fn_GetSQLJobStepInfo_Result1> Fn_GetSQLJobStepInfo(string job_Name)
        {
            var job_NameParameter = job_Name != null ?
                new ObjectParameter("Job_Name", job_Name) :
                new ObjectParameter("Job_Name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Fn_GetSQLJobStepInfo_Result1>("[SkypeIntlMonitoringContext].[Fn_GetSQLJobStepInfo](@Job_Name)", job_NameParameter);
        }
    
        public virtual int UpdateDownloadCount(string fullpath)
        {
            var fullpathParameter = fullpath != null ?
                new ObjectParameter("fullpath", fullpath) :
                new ObjectParameter("fullpath", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateDownloadCount", fullpathParameter);
        }
    }
}
