//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkypeIntlMonitoring.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SqlJob
    {
        public SqlJob()
        {
            this.SqlJobSteps = new HashSet<SqlJobStep>();
        }
    
        public System.Guid SqlJobID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Job_Enabled { get; set; }
        public int Start_Step_ID { get; set; }
        public Nullable<int> Last_Run_Duration { get; set; }
        public Nullable<int> Last_Run_Outcome { get; set; }
        public string Last_Outcome_Message { get; set; }
        public Nullable<System.DateTime> Last_Run_DateTime { get; set; }
        public Nullable<int> LastRunDuration_inMinutes { get; set; }
    
        public virtual ICollection<SqlJobStep> SqlJobSteps { get; set; }
        public virtual JobRunStatus JobRunStatus { get; set; }
    }
}
