//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VsoWorkItemsSync.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoreBugInfosFromFeedback
    {
        public int ID { get; set; }
        public string Status { get; set; }
        public string Project_Name { get; set; }
        public string Project_Area_Path { get; set; }
        public string Project_Iteration_Path { get; set; }
        public string Title { get; set; }
        public string Assigned_To { get; set; }
        public string Reason { get; set; }
        public string Created_By { get; set; }
        public string Priority { get; set; }
        public string Severity { get; set; }
        public string Issue_Type { get; set; }
        public string World_Readiness_Impact { get; set; }
        public string Localization_Impact { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.DateTime> Closed_Date { get; set; }
        public Nullable<System.DateTime> Resolved_Date { get; set; }
    }
}
