//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VsoWorkItemsSync.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoreBugInfo
    {
        public int Loc_Bug_ID { get; set; }
        public int Core_Bug_ID { get; set; }
        public string Loc_Bug_Status { get; set; }
        public string Core_Bug_Status { get; set; }
        public string Core_Project_Name { get; set; }
        public string Core_Project_Area_Path { get; set; }
        public string Core_Project_Iteration_Path { get; set; }
        public string Core_Bug_Title { get; set; }
        public string Core_Bug_Assigned_To { get; set; }
        public string Core_Bug_Reason { get; set; }
        public string Core_Bug_Created_By { get; set; }
        public string Core_Bug_Priority { get; set; }
        public string Core_Bug_Severity { get; set; }
        public string Core_Bug_Issue_Type { get; set; }
        public string Core_Bug_World_Readiness_Impact { get; set; }
        public string Core_Bug_Localization_Impact { get; set; }
        public Nullable<System.DateTime> Core_Bug_Created_Date { get; set; }
        public Nullable<System.DateTime> Core_Bug_Closed_Date { get; set; }
        public Nullable<System.DateTime> Core_Bug_Resolved_Date { get; set; }
    }
}
