//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VsoWorkItemsSync.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImpedimentRevision
    {
        public long ID { get; set; }
        public int Rev { get; set; }
        public string Work_Item_Type { get; set; }
        public string Title { get; set; }
        public string Assigned_To { get; set; }
        public string State { get; set; }
        public string Tags { get; set; }
        public string Area_Path { get; set; }
        public string Changed_By { get; set; }
        public Nullable<System.DateTime> Changed_Date { get; set; }
        public string Closed_By { get; set; }
        public Nullable<System.DateTime> Closed_Date { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.DateTime> Due_Date { get; set; }
        public string Iteration_Path { get; set; }
        public string Resolved_By { get; set; }
        public Nullable<System.DateTime> Resolved_Date { get; set; }
        public string Skype_Priority { get; set; }
        public string Team_Project { get; set; }
        public string Reason { get; set; }
        public string DevSignoff { get; set; }
        public string LocalizationImpact { get; set; }
        public Nullable<int> Swag { get; set; }
        public string WorldReadinessImpact { get; set; }
        public string Description { get; set; }
        public string Severity { get; set; }
        public string ActionPlan { get; set; }
        public string Resolved_Reason { get; set; }
    }
}
