//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VsoWorkItemsSync.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestSuiteTestCaseMapping
    {
        public int Test_Plan_ID { get; set; }
        public int Test_Suite_ID { get; set; }
        public int Test_Case_ID { get; set; }
        public Nullable<int> Test_Suite_Rev { get; set; }
    }
}
