//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VsoWorkItemsSync.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VsoWorkItemsContext : DbContext
    {
        public VsoWorkItemsContext()
            : base("name=VsoWorkItemsContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TestRunResult> TestRunResults { get; set; }
        public virtual DbSet<TestSuiteRevision> TestSuiteRevisions { get; set; }
        public virtual DbSet<TestSuiteTestCaseMapping> TestSuiteTestCaseMappings { get; set; }
        public virtual DbSet<CoreBugInfo> CoreBugInfos { get; set; }
        public virtual DbSet<ImpedimentRevision> ImpedimentRevisions { get; set; }
        public virtual DbSet<TaskRevision> TaskRevisions { get; set; }
        public virtual DbSet<TestCaseRevision> TestCaseRevisions { get; set; }
        public virtual DbSet<TestPlanRevision> TestPlanRevisions { get; set; }
        public virtual DbSet<WorkItemLink> WorkItemLinks { get; set; }
        public virtual DbSet<EnablingSpecificationRevision> EnablingSpecificationRevisions { get; set; }
        public virtual DbSet<EpicRevision> EpicRevisions { get; set; }
        public virtual DbSet<BugRevision> BugRevisions { get; set; }
        public virtual DbSet<WorkItemAttachment> WorkItemAttachments { get; set; }
        public virtual DbSet<CoreBugInfosFromFeedback> CoreBugInfosFromFeedbacks { get; set; }
    }
}
