//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VsoWorkItemsSync.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkItemAttachment
    {
        public int ID { get; set; }
        public int WorkItemID { get; set; }
        public string AttachmentUrl { get; set; }
        public string WorkItemType { get; set; }
        public string AttachmentName { get; set; }
        public string AttachmentComment { get; set; }
    }
}
