//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VsoApi.Report.Wpf.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnablingSpecificationRevision
    {
        public long ID { get; set; }
        public int Rev { get; set; }
        public string Work_Item_Type { get; set; }
        public string Title { get; set; }
        public string Assigned_To { get; set; }
        public string State { get; set; }
        public string Tags { get; set; }
        public string Area_Path { get; set; }
        public string Changed_By { get; set; }
        public Nullable<System.DateTime> Changed_Date { get; set; }
        public string Closed_By { get; set; }
        public Nullable<System.DateTime> Closed_Date { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.DateTime> Due_Date { get; set; }
        public string Iteration_Path { get; set; }
        public string Resolved_By { get; set; }
        public Nullable<System.DateTime> Resolved_Date { get; set; }
        public string Skype_Priority { get; set; }
        public string Team_Project { get; set; }
        public string Reason { get; set; }
        public string DevSignoff { get; set; }
        public string LocalizationImpact { get; set; }
        public string WorldReadinessImpact { get; set; }
        public string Description { get; set; }
        public string Initiator { get; set; }
        public string Review_Required { get; set; }
        public string Blocking { get; set; }
        public string Estimate_Points { get; set; }
        public string Estimate_TShirt { get; set; }
        public string Keywords { get; set; }
        public string Release { get; set; }
        public string Engineering_Effort { get; set; }
        public string Resolved_Reason { get; set; }
    }
}
