//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VsoApi.Report.Wpf.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SkypeVsoWorkItemsEntities : DbContext
    {
        public SkypeVsoWorkItemsEntities()
            : base("name=SkypeVsoWorkItemsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EnablingSpecificationRevision> EnablingSpecificationRevisions { get; set; }
        public virtual DbSet<EpicRevision> EpicRevisions { get; set; }
        public virtual DbSet<TaskRevision> TaskRevisions { get; set; }
        public virtual DbSet<WorkItemLink> WorkItemLinks { get; set; }
    }
}
