//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VsoApi.Report.Wpf.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkItemLink
    {
        public long Source_ID { get; set; }
        public long Target_ID { get; set; }
        public string Link_Type { get; set; }
        public bool Is_Active { get; set; }
        public System.DateTime Changed_Date { get; set; }
    }
}
