//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkypeIntlPortfolio.SyncTool.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GitProjectDocumentation
    {
        public int ProjectDocID { get; set; }
        public string Project_Name { get; set; }
        public string Repository_Name { get; set; }
        public string Document_Path { get; set; }
        public string Branch { get; set; }
    }
}
