#pragma warning disable 1591

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace SkypeIntlPortfolio.Data
{
    public partial class FabricOnboardingsLowLevelStatus
    {
        private string _project;

        public virtual string Project
        {
            get
            {
                return this._project;
            }
            set
            {
                this._project = value;
            }
        }

        private string _lYNCFABWalkTest3;

        public virtual string LYNCFABWalkTest3
        {
            get
            {
                return this._lYNCFABWalkTest3;
            }
            set
            {
                this._lYNCFABWalkTest3 = value;
            }
        }

        private string _lYNCFABWalkTest2;

        public virtual string LYNCFABWalkTest2
        {
            get
            {
                return this._lYNCFABWalkTest2;
            }
            set
            {
                this._lYNCFABWalkTest2 = value;
            }
        }

        private string _lYNCFABWalkTest1;

        public virtual string LYNCFABWalkTest1
        {
            get
            {
                return this._lYNCFABWalkTest1;
            }
            set
            {
                this._lYNCFABWalkTest1 = value;
            }
        }

        private string _lYNCFABCrawlTest7;

        public virtual string LYNCFABCrawlTest7
        {
            get
            {
                return this._lYNCFABCrawlTest7;
            }
            set
            {
                this._lYNCFABCrawlTest7 = value;
            }
        }

        private string _lYNCFABCrawlTest6;

        public virtual string LYNCFABCrawlTest6
        {
            get
            {
                return this._lYNCFABCrawlTest6;
            }
            set
            {
                this._lYNCFABCrawlTest6 = value;
            }
        }

        private string _lYNCFABCrawlTest5;

        public virtual string LYNCFABCrawlTest5
        {
            get
            {
                return this._lYNCFABCrawlTest5;
            }
            set
            {
                this._lYNCFABCrawlTest5 = value;
            }
        }

        private string _lYNCFABCrawlTest4;

        public virtual string LYNCFABCrawlTest4
        {
            get
            {
                return this._lYNCFABCrawlTest4;
            }
            set
            {
                this._lYNCFABCrawlTest4 = value;
            }
        }

        private string _lYNCFABCrawlTest3;

        public virtual string LYNCFABCrawlTest3
        {
            get
            {
                return this._lYNCFABCrawlTest3;
            }
            set
            {
                this._lYNCFABCrawlTest3 = value;
            }
        }

        private string _lYNCFABCrawlTest2;

        public virtual string LYNCFABCrawlTest2
        {
            get
            {
                return this._lYNCFABCrawlTest2;
            }
            set
            {
                this._lYNCFABCrawlTest2 = value;
            }
        }

        private string _lYNCFABCrawlTest1;

        public virtual string LYNCFABCrawlTest1
        {
            get
            {
                return this._lYNCFABCrawlTest1;
            }
            set
            {
                this._lYNCFABCrawlTest1 = value;
            }
        }

        private string _jiraLink;

        public virtual string JiraLink
        {
            get
            {
                return this._jiraLink;
            }
            set
            {
                this._jiraLink = value;
            }
        }

        private string _aAPTEpicTasks;

        public virtual string AAPTEpicTasks
        {
            get
            {
                return this._aAPTEpicTasks;
            }
            set
            {
                this._aAPTEpicTasks = value;
            }
        }
    }
}

#pragma warning restore 1591