#pragma warning disable 1591

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace SkypeIntlPortfolio.Data
{
    public partial class FabricOnboardingsHighLevelStatus
    {
        private string _project;

        public virtual string Project
        {
            get
            {
                return this._project;
            }
            set
            {
                this._project = value;
            }
        }

        private string _phase;

        public virtual string Phase
        {
            get
            {
                return this._phase;
            }
            set
            {
                this._phase = value;
            }
        }
    }
}

#pragma warning restore 1591