//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkypeIntlPortfolio.Ajax
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public Location()
        {
            this.Products_New = new HashSet<Products_New>();
            this.Products_New1 = new HashSet<Products_New>();
            this.VacationInfoes = new HashSet<VacationInfo>();
        }
    
        public int LocationKey { get; set; }
        public string Location1 { get; set; }
    
        public virtual ICollection<Products_New> Products_New { get; set; }
        public virtual ICollection<Products_New> Products_New1 { get; set; }
        public virtual ICollection<VacationInfo> VacationInfoes { get; set; }
    }
}
