//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkypeIntlPortfolio.Ajax
{
    using System;
    using System.Collections.Generic;
    
    public partial class UILanguage
    {
        public UILanguage()
        {
            this.ResourceFiles = new HashSet<ResourceFile>();
        }
    
        public int UILanguagesKey { get; set; }
        public Nullable<int> ProductKey { get; set; }
        public Nullable<int> LanguageKey { get; set; }
        public Nullable<bool> Language_Released { get; set; }
        public Nullable<bool> Language_Blocked { get; set; }
        public Nullable<bool> Language_Planned { get; set; }
        public Nullable<System.DateTime> Release_Date { get; set; }
        public string Blocked_Reason { get; set; }
    
        public virtual BasicLanguageList BasicLanguageList { get; set; }
        public virtual ICollection<ResourceFile> ResourceFiles { get; set; }
        public virtual Products_New Products_New { get; set; }
    }
}
