//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkypeIntlPortfolio.Ajax
{
    using System;
    using System.Collections.Generic;
    
    public partial class VacationInfo
    {
        public VacationInfo()
        {
            this.Products_New = new HashSet<Products_New>();
            this.Locations = new HashSet<Location>();
        }
    
        public int VacationID { get; set; }
        public string VacationName { get; set; }
        public string VacationDescription { get; set; }
        public System.DateTime VacationStartDate { get; set; }
        public System.DateTime VacationEndDate { get; set; }
        public int UICategoryID { get; set; }
    
        public virtual UIVacationCategory UIVacationCategory { get; set; }
        public virtual ICollection<Products_New> Products_New { get; set; }
        public virtual ICollection<Location> Locations { get; set; }
    }
}
