//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkypeLocFeedbackAndReviewBot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SkypeLocFeedbackAndReviewBot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string AnswerNo {
            get {
                return ResourceManager.GetString("AnswerNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string AnswerYes {
            get {
                return ResourceManager.GetString("AnswerYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can provide you with strings to review in your native language and offer you the change to suggest better translations!.
        /// </summary>
        public static string Capabilities {
            get {
                return ResourceManager.GetString("Capabilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry do not speak that language :(.
        /// </summary>
        public static string Command_DoNotUnderstandLangauge {
            get {
                return ResourceManager.GetString("Command_DoNotUnderstandLangauge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please type language name(in english) in what this buf is occuring?(For example German,Russian,Crezh,Estonian), if this issue not language specific please type [Non Language-Specific]..
        /// </summary>
        public static string Command_In_What_BugLanguage {
            get {
                return ResourceManager.GetString("Command_In_What_BugLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In what language you would like to speak with me?.
        /// </summary>
        public static string Command_In_What_Language {
            get {
                return ResourceManager.GetString("Command_In_What_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick one Language.
        /// </summary>
        public static string Command_Select_One {
            get {
                return ResourceManager.GetString("Command_Select_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oki-doki-now switching to {0}.
        /// </summary>
        public static string Command_SwtichToLanguage {
            get {
                return ResourceManager.GetString("Command_SwtichToLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great, thanks. Is this feedback for a Consumer or the Skype for Business product?.
        /// </summary>
        public static string ConsumerOrSfbRequest {
            get {
                return ResourceManager.GetString("ConsumerOrSfbRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey, my new Friend! Lets improve the localization quality of Skype!.
        /// </summary>
        public static string ContactAdded {
            get {
                return ResourceManager.GetString("ContactAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to continue with evaluating translations?.
        /// </summary>
        public static string ContinueWithEvaluations {
            get {
                return ResourceManager.GetString("ContinueWithEvaluations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Discover_Female {
            get {
                return ResourceManager.GetString("Discover_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Discover_Male {
            get {
                return ResourceManager.GetString("Discover_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Discover_Other {
            get {
                return ResourceManager.GetString("Discover_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unspecified.
        /// </summary>
        public static string Discover_Unspecified {
            get {
                return ResourceManager.GetString("Discover_Unspecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is your gender?.
        /// </summary>
        public static string Discover_What_Gender {
            get {
                return ResourceManager.GetString("Discover_What_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I would like to learn more about you!.
        /// </summary>
        public static string DiscoverUser {
            get {
                return ResourceManager.GetString("DiscoverUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So you are a master of the {1} language..
        /// </summary>
        public static string DiscoverUserGoodReponse {
            get {
                return ResourceManager.GetString("DiscoverUserGoodReponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What are the languages, that you master at a very good level?.
        /// </summary>
        public static string DiscoverUserLanguageGood {
            get {
                return ResourceManager.GetString("DiscoverUserLanguageGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is your native language?.
        /// </summary>
        public static string DiscoverUserLanguageNative {
            get {
                return ResourceManager.GetString("DiscoverUserLanguageNative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From what I understood your native language is {0}..
        /// </summary>
        public static string DiscoverUserNativeResponce {
            get {
                return ResourceManager.GetString("DiscoverUserNativeResponce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to judge the current translation quality between {0} and {1}?.
        /// </summary>
        public static string DiscoverUserQualityJudge {
            get {
                return ResourceManager.GetString("DiscoverUserQualityJudge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please type-in your suggestion! And then press Enter (Send message).
        /// </summary>
        public static string Evaluate_EnterSuggestion {
            get {
                return ResourceManager.GetString("Evaluate_EnterSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to evaluate some translation quality?.
        /// </summary>
        public static string Evaluate_Init {
            get {
                return ResourceManager.GetString("Evaluate_Init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terrible. I can translate better!.
        /// </summary>
        public static string EvaluateString_Bad_Action {
            get {
                return ResourceManager.GetString("EvaluateString_Bad_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excellent translation.
        /// </summary>
        public static string EvaluateString_Best_Action {
            get {
                return ResourceManager.GetString("EvaluateString_Best_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is fine translation.
        /// </summary>
        public static string EvaluateString_Medium_Action {
            get {
                return ResourceManager.GetString("EvaluateString_Medium_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluate a Translation from source &apos;{0}&apos;  | {1}.
        /// </summary>
        public static string EvaluateString_Source {
            get {
                return ResourceManager.GetString("EvaluateString_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to upload attachment or not?.
        /// </summary>
        public static string FeedbackAttachmentsRequest {
            get {
                return ResourceManager.GetString("FeedbackAttachmentsRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload screenshots or attachments if you have them. The more detail, the easier it is to fix!.
        /// </summary>
        public static string FeedbackAttachmentsUploadRequest {
            get {
                return ResourceManager.GetString("FeedbackAttachmentsUploadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you! Ok, please enter your feedback when ready. Include if possible in one message (original translation, suggested translation and english text. And be as detailed in comment as possible)
        ///.
        /// </summary>
        public static string FeedBackContentRequest {
            get {
                return ResourceManager.GetString("FeedBackContentRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your feedback has been logged - work item {0} has been created, and will be triaged and actioned as soon as possible..
        /// </summary>
        public static string FeedbackLoggedSuccessfullyMessage {
            get {
                return ResourceManager.GetString("FeedbackLoggedSuccessfullyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you. Now, can you tell me the specific product this is for, or is it generic?.
        /// </summary>
        public static string FeedbackRange {
            get {
                return ResourceManager.GetString("FeedbackRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback received! Generating a work item now.
        /// </summary>
        public static string FeedbackReceivedMessage {
            get {
                return ResourceManager.GetString("FeedbackReceivedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Meaning of Life, the Universe, and Everything.
        /// </summary>
        public static string Hack42 {
            get {
                return ResourceManager.GetString("Hack42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a product name.
        /// </summary>
        public static string ProductNameInputRequest {
            get {
                return ResourceManager.GetString("ProductNameInputRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input &quot;bug&quot; to active the process.
        /// </summary>
        public static string ProvidefeedbackRequest {
            get {
                return ResourceManager.GetString("ProvidefeedbackRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please put a mark on translation quality (1-10, with 10 - the best and 1 - the worst) {0} language phrase &quot;{1}&quot; (id {2}) is translated as &quot;{3}&quot; in {4} language!.
        /// </summary>
        public static string QualityCompareStrings {
            get {
                return ResourceManager.GetString("QualityCompareStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wow! That sounds great! We will give a cookie to the translators. Thank you!.
        /// </summary>
        public static string QualityExcelent {
            get {
                return ResourceManager.GetString("QualityExcelent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is passable. Would you like to suggest something better?.
        /// </summary>
        public static string QualityMedicore {
            get {
                return ResourceManager.GetString("QualityMedicore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouch, thats too bad. Can you suggest a better translation?.
        /// </summary>
        public static string QualityYouCanBetter {
            get {
                return ResourceManager.GetString("QualityYouCanBetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for all the fish!.
        /// </summary>
        public static string RemovedContact {
            get {
                return ResourceManager.GetString("RemovedContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;root&gt;
        ///  &lt;!-- 
        ///    Microsoft ResX Schema 
        ///    
        ///    Version 2.0
        ///    
        ///    The primary goals of this format is to allow a simple XML format 
        ///    that is mostly human readable. The generation and parsing of the 
        ///    various data types are done through the TypeConverter classes 
        ///    associated with the data types.
        ///    
        ///    Example:
        ///    
        ///    ... ado.net/XML headers &amp; schema ...
        ///    &lt;resheader name=&quot;resmimetype&quot;&gt;text/microsoft-resx&lt;/resheader&gt;
        ///    &lt;resheader n [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Resources {
            get {
                return ResourceManager.GetString("Resources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;root&gt;
        ///  &lt;!-- 
        ///    Microsoft ResX Schema 
        ///    
        ///    Version 2.0
        ///    
        ///    The primary goals of this format is to allow a simple XML format 
        ///    that is mostly human readable. The generation and parsing of the 
        ///    various data types are done through the TypeConverter classes 
        ///    associated with the data types.
        ///    
        ///    Example:
        ///    
        ///    ... ado.net/XML headers &amp; schema ...
        ///    &lt;resheader name=&quot;resmimetype&quot;&gt;text/microsoft-resx&lt;/resheader&gt;
        ///    &lt;resheader n [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Resources_de_DE {
            get {
                return ResourceManager.GetString("Resources_de_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;root&gt;
        ///  &lt;resheader name=&quot;resmimetype&quot;&gt;
        ///    &lt;value&gt;text/microsoft-resx&lt;/value&gt;
        ///  &lt;/resheader&gt;
        ///  &lt;resheader name=&quot;version&quot;&gt;
        ///    &lt;value&gt;2.0&lt;/value&gt;
        ///  &lt;/resheader&gt;
        ///  &lt;resheader name=&quot;reader&quot;&gt;
        ///    &lt;value&gt;System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089&lt;/value&gt;
        ///  &lt;/resheader&gt;
        ///  &lt;resheader name=&quot;writer&quot;&gt;
        ///    &lt;value&gt;System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Resources_it_IT {
            get {
                return ResourceManager.GetString("Resources_it_IT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;root&gt;
        ///  &lt;resheader name=&quot;resmimetype&quot;&gt;
        ///    &lt;value&gt;text/microsoft-resx&lt;/value&gt;
        ///  &lt;/resheader&gt;
        ///  &lt;resheader name=&quot;version&quot;&gt;
        ///    &lt;value&gt;2.0&lt;/value&gt;
        ///  &lt;/resheader&gt;
        ///  &lt;resheader name=&quot;reader&quot;&gt;
        ///    &lt;value&gt;System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089&lt;/value&gt;
        ///  &lt;/resheader&gt;
        ///  &lt;resheader name=&quot;writer&quot;&gt;
        ///    &lt;value&gt;System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Resources_lv_LV {
            get {
                return ResourceManager.GetString("Resources_lv_LV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;root&gt;
        ///  &lt;resheader name=&quot;resmimetype&quot;&gt;
        ///    &lt;value&gt;text/microsoft-resx&lt;/value&gt;
        ///  &lt;/resheader&gt;
        ///  &lt;resheader name=&quot;version&quot;&gt;
        ///    &lt;value&gt;2.0&lt;/value&gt;
        ///  &lt;/resheader&gt;
        ///  &lt;resheader name=&quot;reader&quot;&gt;
        ///    &lt;value&gt;System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089&lt;/value&gt;
        ///  &lt;/resheader&gt;
        ///  &lt;resheader name=&quot;writer&quot;&gt;
        ///    &lt;value&gt;System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Resources_ru_RU {
            get {
                return ResourceManager.GetString("Resources_ru_RU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; encoding=&apos;utf-8&apos;?&gt;
        ///&lt;SettingsFile xmlns=&quot;http://schemas.microsoft.com/VisualStudio/2004/01/settings&quot; CurrentProfile=&quot;(Default)&quot;&gt;
        ///  &lt;Profiles&gt;
        ///    &lt;Profile Name=&quot;(Default)&quot; /&gt;
        ///  &lt;/Profiles&gt;
        ///&lt;/SettingsFile&gt;
        ///.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you. Now, can you tell me the specific product this is for, or is it generic?.
        /// </summary>
        public static string SpecifiedProOrGeneric {
            get {
                return ResourceManager.GetString("SpecifiedProOrGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi, I&apos;m {0}. You can report localization bugs to me, so that they can be fixed. Let&apos;s drive language quality together! To report a bug, just type &quot;bug&quot;.  (You can enter &apos;\reset&apos; anytime to restart the operation).
        /// </summary>
        public static string StartProcess {
            get {
                return ResourceManager.GetString("StartProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string StatusReport {
            get {
                return ResourceManager.GetString("StatusReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have translated {0} and reviewed {1} language pairs.
        /// </summary>
        public static string StatusReportAnswer {
            get {
                return ResourceManager.GetString("StatusReportAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have translated {0} and reviewed {1} language pairs. {2} of your translations are used in production! Good job!.
        /// </summary>
        public static string StatusReportExtendedAnswer {
            get {
                return ResourceManager.GetString("StatusReportExtendedAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string String10 {
            get {
                return ResourceManager.GetString("String10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string String11 {
            get {
                return ResourceManager.GetString("String11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unspecified.
        /// </summary>
        public static string String12 {
            get {
                return ResourceManager.GetString("String12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is your gender?.
        /// </summary>
        public static string String13 {
            get {
                return ResourceManager.GetString("String13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I would like to learn more about you!.
        /// </summary>
        public static string String14 {
            get {
                return ResourceManager.GetString("String14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So you are a master of the {1} language..
        /// </summary>
        public static string String15 {
            get {
                return ResourceManager.GetString("String15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What are the languages, that you master at a very good level?.
        /// </summary>
        public static string String16 {
            get {
                return ResourceManager.GetString("String16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is your native language?.
        /// </summary>
        public static string String17 {
            get {
                return ResourceManager.GetString("String17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From what I understood your native language is {0}..
        /// </summary>
        public static string String18 {
            get {
                return ResourceManager.GetString("String18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to judge the current translation quality between {0} and {1}?.
        /// </summary>
        public static string String19 {
            get {
                return ResourceManager.GetString("String19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can provide you with strings to review in your native language and offer you the change to suggest better translations!.
        /// </summary>
        public static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please type-in your suggestion! And then press Enter (Send message).
        /// </summary>
        public static string String20 {
            get {
                return ResourceManager.GetString("String20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to evaluate some translation quality?.
        /// </summary>
        public static string String21 {
            get {
                return ResourceManager.GetString("String21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terrible. I can translate better!.
        /// </summary>
        public static string String22 {
            get {
                return ResourceManager.GetString("String22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excellent translation.
        /// </summary>
        public static string String23 {
            get {
                return ResourceManager.GetString("String23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is fine translation.
        /// </summary>
        public static string String24 {
            get {
                return ResourceManager.GetString("String24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluate a Translation from source &apos;{0}&apos;  | {1}.
        /// </summary>
        public static string String25 {
            get {
                return ResourceManager.GetString("String25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Meaning of Life, the Universe, and Everything.
        /// </summary>
        public static string String26 {
            get {
                return ResourceManager.GetString("String26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please put a mark on translation quality (1-10, with 10 - the best and 1 - the worst) {0} language phrase &quot;{1}&quot; (id {2}) is translated as &quot;{3}&quot; in {4} language!.
        /// </summary>
        public static string String27 {
            get {
                return ResourceManager.GetString("String27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wow! That sounds great! We will give a cookie to the translators. Thank you!.
        /// </summary>
        public static string String28 {
            get {
                return ResourceManager.GetString("String28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is passable. Would you like to suggest something better?.
        /// </summary>
        public static string String29 {
            get {
                return ResourceManager.GetString("String29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry do not speak that language :(.
        /// </summary>
        public static string String3 {
            get {
                return ResourceManager.GetString("String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouch, that&apos;s too bad. Can you suggest a better translation?.
        /// </summary>
        public static string String30 {
            get {
                return ResourceManager.GetString("String30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for all the fish!.
        /// </summary>
        public static string String31 {
            get {
                return ResourceManager.GetString("String31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string String32 {
            get {
                return ResourceManager.GetString("String32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have translated {0} and reviewed {1} language pairs.
        /// </summary>
        public static string String33 {
            get {
                return ResourceManager.GetString("String33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have translated {0} and reviewed {1} language pairs. {2} of your translations are used in production! Good job!.
        /// </summary>
        public static string String34 {
            get {
                return ResourceManager.GetString("String34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you, your contribution will make a better user experience for you and other users!.
        /// </summary>
        public static string String35 {
            get {
                return ResourceManager.GetString("String35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey, new friend! I am LocaLiz. You help me with giving feedback on translation quality..
        /// </summary>
        public static string String36 {
            get {
                return ResourceManager.GetString("String36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In what language you would like to speak with me?.
        /// </summary>
        public static string String4 {
            get {
                return ResourceManager.GetString("String4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick one Language.
        /// </summary>
        public static string String5 {
            get {
                return ResourceManager.GetString("String5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oki-doki-now switching to {0}.
        /// </summary>
        public static string String6 {
            get {
                return ResourceManager.GetString("String6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey, my new Friend! Lets improve the localization quality of Skype!.
        /// </summary>
        public static string String7 {
            get {
                return ResourceManager.GetString("String7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to continue with evaluating translations?.
        /// </summary>
        public static string String8 {
            get {
                return ResourceManager.GetString("String8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string String9 {
            get {
                return ResourceManager.GetString("String9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you, your contribution will make a better user experience for you and other users!.
        /// </summary>
        public static string ThankYou {
            get {
                return ResourceManager.GetString("ThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for using Feedback Bot. Would you like to provide more feedback?.
        /// </summary>
        public static string ThankYouMessage {
            get {
                return ResourceManager.GetString("ThankYouMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hank you! Ok, please enter your feedback when ready. Please also include screenshots or attachments if you have them. The more detail, the easier it is to fix!.
        /// </summary>
        public static string VsoCreationHint {
            get {
                return ResourceManager.GetString("VsoCreationHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey, new friend! I am Feedback Bot. You help me with giving feedback on translation quality. .
        /// </summary>
        public static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
    }
}
