//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteelheadDataParser.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Staging_SkypeLocalizationDataWEntities : DbContext
    {
        public Staging_SkypeLocalizationDataWEntities()
            : base("name=Staging_SkypeLocalizationDataWEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Staging_SteelheadDataParsed> Staging_SteelheadDataParsed { get; set; }
    
        public virtual ObjectResult<GetStagingFabricBackupSteelheadData_Result> GetStagingFabricBackupSteelheadData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetStagingFabricBackupSteelheadData_Result>("GetStagingFabricBackupSteelheadData");
        }
    }
}
