//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkypeIntlPortfolio.Ajax.UserControls.ProductProfile.People {
    
    
    public partial class PeopleControl {
        
        /// <summary>
        /// updatePanel_ppPeopleControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel updatePanel_ppPeopleControl;
        
        /// <summary>
        /// radTextBox_MSPMOwner control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.Web.UI.RadTextBox radTextBox_MSPMOwner;
        
        /// <summary>
        /// radTextBox_iSSowner control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.Web.UI.RadTextBox radTextBox_iSSowner;
        
        /// <summary>
        /// radTextBox_ISSIPE control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.Web.UI.RadTextBox radTextBox_ISSIPE;
        
        /// <summary>
        /// radTextBox_ISSTester control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.Web.UI.RadTextBox radTextBox_ISSTester;
        
        /// <summary>
        /// radTextBox_CoreTeamContact control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.Web.UI.RadTextBox radTextBox_CoreTeamContact;
        
        /// <summary>
        /// radTextBox_CoreTeamSharePoint control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.Web.UI.RadTextBox radTextBox_CoreTeamSharePoint;
        
        /// <summary>
        /// radTextBox_TelemetryContact control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.Web.UI.RadTextBox radTextBox_TelemetryContact;
        
        /// <summary>
        /// radTextBox_CoreDesignContact control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.Web.UI.RadTextBox radTextBox_CoreDesignContact;
        
        /// <summary>
        /// radTextBox_CoreEngineeringContact control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.Web.UI.RadTextBox radTextBox_CoreEngineeringContact;
        
        /// <summary>
        /// radListBox_CoreTeamLocation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.Web.UI.RadListBox radListBox_CoreTeamLocation;
        
        /// <summary>
        /// radioButtonList_MSPMOwnerLocation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RadioButtonList radioButtonList_MSPMOwnerLocation;
        
        /// <summary>
        /// RadButton_tab_people_SaveAndNextPage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.Web.UI.RadButton RadButton_tab_people_SaveAndNextPage;
    }
}
