using SteelheadDataParser.Core;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SteelheadDataParser.Model
{
    /// <summary>
    /// This is an extension class which consists of  partial properties of this class,
    /// others' properties are generated by entity framework automatically
    ///
    /// </summary>
    partial class Staging_FabricBackup_SteelheadDataParsed
    {
        [ImportIgnore]
        public string SteelheadData { get; set; }
    }
}